// commandkit_reference.js — Notrya AI | CommandKit Clinical Reference Data
// Place in: src/lib/commandkit_reference.js
// Import in CommandKit.jsx: import { REFERENCE_DB, REF_CATEGORIES } from "@/lib/commandkit_reference";

export const REF_CATEGORIES = {
  scoring:   { label: "Scoring Systems",   color: "#A78BFA" },
  criteria:  { label: "Clinical Criteria", color: "#34D399" },
  checklist: { label: "Checklists",        color: "#F59E0B" },
  threshold: { label: "Thresholds",        color: "#12CCE6" },
  formula:   { label: "Formulas",          color: "#FB923C" },
};

export const REFERENCE_DB = {

  heart_score: {
    id: "heart_score",
    name: "HEART Score",
    shortName: "HEART",
    category: "scoring",
    clinicalUse: "ACS risk stratification in chest pain — predicts 30-day MACE",
    tags: ["chest pain", "ACS", "MACE", "troponin", "cardiac", "risk"],
    scenarios: ["acls"],
    items: [
      { label: "History", detail: "Slightly suspicious: 0 | Moderately suspicious: 1 | Highly suspicious: 2" },
      { label: "ECG", detail: "Normal: 0 | Non-specific repolarization: 1 | Significant ST deviation: 2" },
      { label: "Age", detail: "< 45: 0 | 45-64: 1 | ≥ 65: 2" },
      { label: "Risk Factors", detail: "None: 0 | 1-2 or obesity: 1 | ≥ 3 or DM or known atherosclerosis: 2" },
      { label: "Troponin", detail: "Normal: 0 | 1-3x ULN: 1 | > 3x ULN: 2" },
    ],
    interpretation: [
      { range: "0-3", label: "Low Risk", action: "1.7% 30-day MACE. Safe for early discharge.", color: "#34D399" },
      { range: "4-6", label: "Moderate Risk", action: "Observe, serial troponins, stress test or cath.", color: "#F59E0B" },
      { range: "7-10", label: "High Risk", action: "50-65% MACE. Early invasive strategy.", color: "#FF4444" },
    ],
    pearl: "HEART ≥ 4 in ED: sensitivity 99%, specificity 55% for 30-day MACE.",
    source: "Six ACS 2010; HEART Pathway 2016",
    hubLink: "ECGHub",
  },

  perc_rule: {
    id: "perc_rule",
    name: "PERC Rule",
    shortName: "PERC",
    category: "criteria",
    clinicalUse: "Rule OUT PE without imaging — only apply in low pre-test probability",
    tags: ["PE", "pulmonary embolism", "dyspnea", "chest pain", "Wells"],
    scenarios: ["shock"],
    items: [
      { label: "Age < 50" },
      { label: "HR < 100 bpm" },
      { label: "SpO2 ≥ 95% on room air" },
      { label: "No unilateral leg swelling" },
      { label: "No hemoptysis" },
      { label: "No trauma or surgery within 4 weeks" },
      { label: "No prior DVT or PE" },
      { label: "No exogenous estrogen use" },
    ],
    interpretation: [
      { range: "All 8 met", label: "PERC Negative", action: "PE excluded if low pre-test probability. No further workup.", color: "#34D399" },
      { range: "Any absent", label: "PERC Positive", action: "Proceed with D-dimer or CTPA per Wells score.", color: "#FF4444" },
    ],
    pearl: "PERC only valid when gestalt pre-test probability < 15%. Never apply to moderate or high pre-test probability.",
    source: "Kline et al, J Thromb Haemost 2004; ACEP Guidelines",
    hubLink: null,
  },

  wells_pe: {
    id: "wells_pe",
    name: "Wells Score — PE",
    shortName: "Wells PE",
    category: "scoring",
    clinicalUse: "Pre-test probability for pulmonary embolism",
    tags: ["PE", "pulmonary embolism", "Wells", "D-dimer", "CTPA"],
    scenarios: ["shock"],
    items: [
      { label: "DVT signs/symptoms", points: 3 },
      { label: "PE more likely than alternative diagnosis", points: 3 },
      { label: "HR > 100 bpm", points: 1.5 },
      { label: "Immobilization or surgery within 4 weeks", points: 1.5 },
      { label: "Prior DVT or PE", points: 1.5 },
      { label: "Hemoptysis", points: 1 },
      { label: "Malignancy (on treatment or within 6 months)", points: 1 },
    ],
    interpretation: [
      { range: "≤ 1", label: "Low", action: "D-dimer. If negative, PE excluded.", color: "#34D399" },
      { range: "2-6", label: "Moderate", action: "D-dimer or CTPA based on clinical judgment.", color: "#F59E0B" },
      { range: "> 6", label: "High", action: "CTPA directly. D-dimer not useful.", color: "#FF4444" },
    ],
    pearl: "Two-tier simplification: ≤ 4 = PE unlikely (D-dimer); > 4 = PE likely (CTPA).",
    source: "Wells et al, Ann Intern Med 2001",
    hubLink: null,
  },

  qsofa: {
    id: "qsofa",
    name: "qSOFA",
    shortName: "qSOFA",
    category: "criteria",
    clinicalUse: "Rapid bedside sepsis-related organ dysfunction screen",
    tags: ["sepsis", "infection", "organ dysfunction", "shock"],
    scenarios: ["sepsis"],
    items: [
      { label: "Respiratory rate ≥ 22/min", points: 1 },
      { label: "Altered mentation (GCS < 15)", points: 1 },
      { label: "SBP ≤ 100 mmHg", points: 1 },
    ],
    interpretation: [
      { range: "0-1", label: "Low Risk", action: "Low risk of poor outcome. Monitor.", color: "#34D399" },
      { range: "≥ 2", label: "High Risk", action: "High risk — initiate sepsis protocol, consider ICU.", color: "#FF4444" },
    ],
    pearl: "qSOFA ≥ 2 predicts mortality better than SIRS outside the ICU. Use alongside clinical gestalt.",
    source: "Sepsis-3 Consensus, JAMA 2016",
    hubLink: "SepsisHub",
  },

  curb65: {
    id: "curb65",
    name: "CURB-65",
    shortName: "CURB-65",
    category: "scoring",
    clinicalUse: "Pneumonia severity — inpatient vs outpatient disposition",
    tags: ["pneumonia", "CAP", "sepsis", "disposition", "ICU"],
    scenarios: ["sepsis"],
    items: [
      { label: "Confusion (new)", points: 1 },
      { label: "Urea / BUN > 19 mg/dL", points: 1 },
      { label: "Respiratory rate ≥ 30/min", points: 1 },
      { label: "BP: SBP < 90 or DBP ≤ 60 mmHg", points: 1 },
      { label: "Age ≥ 65", points: 1 },
    ],
    interpretation: [
      { range: "0-1", label: "Low", action: "Outpatient. Mortality ~1.5%.", color: "#34D399" },
      { range: "2", label: "Moderate", action: "Short inpatient or supervised outpatient. Mortality ~9%.", color: "#F59E0B" },
      { range: "3-5", label: "Severe", action: "Inpatient — ICU if 4-5. Mortality up to 57%.", color: "#FF4444" },
    ],
    pearl: "CURB-65 ≥ 3: consider ICU. Combine with PSI/PORT for borderline cases.",
    source: "Lim et al, Thorax 2003; BTS Guidelines",
    hubLink: "SepsisHub",
  },

  nexus: {
    id: "nexus",
    name: "NEXUS Criteria",
    shortName: "NEXUS",
    category: "criteria",
    clinicalUse: "Clear cervical spine clinically without imaging in blunt trauma",
    tags: ["c-spine", "cervical", "trauma", "clearance", "CT", "x-ray"],
    scenarios: ["trauma"],
    items: [
      { label: "No posterior midline cervical tenderness" },
      { label: "No focal neurological deficit" },
      { label: "Normal alertness (GCS 15, no intoxication)" },
      { label: "No painful distracting injury" },
      { label: "No evidence of intoxication" },
    ],
    interpretation: [
      { range: "All 5 met", label: "Low Risk", action: "C-spine cleared clinically. No imaging needed. Sensitivity 99.6%.", color: "#34D399" },
      { range: "Any absent", label: "Image Required", action: "CT C-spine preferred over plain films in blunt trauma.", color: "#FF4444" },
    ],
    pearl: "Canadian C-Spine Rule is more specific (fewer unnecessary CTs) but more complex. NEXUS is faster at bedside.",
    source: "Hoffman et al, NEJM 2000",
    hubLink: null,
  },

  abcd2: {
    id: "abcd2",
    name: "ABCD2 Score",
    shortName: "ABCD2",
    category: "scoring",
    clinicalUse: "2-day stroke risk after TIA — guides admission vs outpatient workup",
    tags: ["TIA", "stroke", "risk", "neurology", "admission"],
    scenarios: ["stroke"],
    items: [
      { label: "Age ≥ 60", points: 1 },
      { label: "BP ≥ 140/90 at presentation", points: 1 },
      { label: "Clinical: Unilateral weakness", points: 2 },
      { label: "Clinical: Speech disturbance without weakness", points: 1 },
      { label: "Duration ≥ 60 min", points: 2 },
      { label: "Duration 10-59 min", points: 1 },
      { label: "Diabetes", points: 1 },
    ],
    interpretation: [
      { range: "0-3", label: "Low Risk", action: "2-day stroke risk ~1%. Outpatient workup acceptable.", color: "#34D399" },
      { range: "4-5", label: "Moderate Risk", action: "2-day stroke risk ~4%. Expedited workup within 24h.", color: "#F59E0B" },
      { range: "6-7", label: "High Risk", action: "2-day stroke risk ~8%. Admit for rapid inpatient workup.", color: "#FF4444" },
    ],
    pearl: "Up to 10-20% of high-risk TIA patients stroke within 90 days without treatment. Do not discharge without workup plan.",
    source: "Johnston et al, Lancet 2007; AHA/ASA TIA Guidelines",
    hubLink: "StrokeHub",
  },

  tpa_checklist: {
    id: "tpa_checklist",
    name: "tPA Eligibility — Ischemic Stroke",
    shortName: "tPA Checklist",
    category: "checklist",
    clinicalUse: "Inclusion and exclusion criteria before alteplase administration",
    tags: ["tPA", "alteplase", "stroke", "thrombolysis", "inclusion", "exclusion"],
    scenarios: ["stroke"],
    items: [
      { label: "INCLUSION", isHeader: true },
      { label: "Ischemic stroke with measurable neurological deficit" },
      { label: "Symptom onset within 3.0 h (up to 4.5 h if extended criteria met)" },
      { label: "Age ≥ 18" },
      { label: "ABSOLUTE EXCLUSIONS", isHeader: true },
      { label: "CT: hemorrhage or > 1/3 MCA territory infarct" },
      { label: "BP > 185/110 at time of treatment" },
      { label: "Active bleeding or coagulopathy" },
      { label: "Platelets < 100,000 or INR > 1.7" },
      { label: "Major surgery or serious trauma within 14 days" },
      { label: "GI/GU hemorrhage within 21 days" },
      { label: "Prior stroke + diabetes (combined)" },
      { label: "Stroke or head trauma within 3 months" },
      { label: "RELATIVE EXCLUSIONS (3-4.5h window)", isHeader: true },
      { label: "Age > 80" },
      { label: "NIHSS > 25" },
      { label: "Any oral anticoagulant use" },
    ],
    interpretation: [
      { range: "Inclusions met, no absolute exclusions", label: "Eligible", action: "Alteplase 0.9 mg/kg IV (max 90 mg). 10% bolus, remainder over 60 min.", color: "#34D399" },
      { range: "Any absolute exclusion present", label: "Contraindicated", action: "No tPA. Consider mechanical thrombectomy if LVO on CTA.", color: "#FF4444" },
    ],
    pearl: "Confirm BP < 185/110 immediately before giving tPA. Treat with labetalol or nicardipine first if needed.",
    source: "AHA/ASA Acute Ischemic Stroke Guidelines 2019",
    hubLink: "StrokeHub",
  },

  stemi_criteria: {
    id: "stemi_criteria",
    name: "STEMI Criteria",
    shortName: "STEMI",
    category: "threshold",
    clinicalUse: "ECG criteria for ST-elevation MI — triggers emergent reperfusion",
    tags: ["STEMI", "ECG", "ST elevation", "MI", "ACS", "PCI", "cath lab"],
    scenarios: ["acls"],
    items: [
      { label: "ST elevation at J-point in ≥ 2 contiguous leads:" },
      { label: "Limb leads (I, II, aVL, aVF): ≥ 1 mm" },
      { label: "V2-V3 men ≥ 40y: ≥ 2 mm" },
      { label: "V2-V3 men < 40y: ≥ 2.5 mm" },
      { label: "V2-V3 women: ≥ 1.5 mm" },
      { label: "All other precordial leads: ≥ 1 mm" },
      { label: "New LBBB with ischemic symptoms (Sgarbossa criteria)" },
      { label: "Posterior STEMI: ST depression V1-V4 + tall R in V1-V2" },
      { label: "RV infarct: STE in V3R/V4R with inferior STEMI" },
    ],
    interpretation: [
      { range: "Criteria met", label: "STEMI Activation", action: "Cath lab activation. Door-to-balloon ≤ 90 min (PCI) or ≤ 30 min (lytic if PCI unavailable).", color: "#FF4444" },
    ],
    pearl: "Inferior STEMI: always get right-sided leads. RV infarct (STE in V4R) — avoid nitrates, give fluids.",
    source: "AHA/ACC 2013 STEMI Guidelines; Fourth Universal MI Definition",
    hubLink: "ECGHub",
  },

  ottawa_ankle: {
    id: "ottawa_ankle",
    name: "Ottawa Ankle Rules",
    shortName: "Ottawa Ankle",
    category: "criteria",
    clinicalUse: "Need for ankle or foot X-ray after injury",
    tags: ["ankle", "foot", "fracture", "x-ray", "trauma", "orthopedic"],
    scenarios: ["trauma"],
    items: [
      { label: "ANKLE X-RAY if pain in malleolar zone PLUS:", isHeader: true },
      { label: "Bony tenderness at posterior edge / tip of lateral malleolus" },
      { label: "Bony tenderness at posterior edge / tip of medial malleolus" },
      { label: "Inability to bear weight (4 steps) now AND in ED" },
      { label: "FOOT X-RAY if pain in midfoot zone PLUS:", isHeader: true },
      { label: "Bony tenderness at base of 5th metatarsal" },
      { label: "Bony tenderness at navicular" },
      { label: "Inability to bear weight (4 steps) now AND in ED" },
    ],
    interpretation: [
      { range: "No criteria", label: "No X-ray", action: "98-100% sensitivity for fracture. Safe to discharge without imaging.", color: "#34D399" },
      { range: "Any criteria", label: "X-ray Indicated", action: "Obtain ankle and/or foot X-ray series.", color: "#F59E0B" },
    ],
    pearl: "Not validated in children < 18 or pregnancy. Sensitivity ~97-99% for clinically significant fractures.",
    source: "Stiell et al, JAMA 1993; BMJ 1994",
    hubLink: "OrthoHub",
  },

  dka_criteria: {
    id: "dka_criteria",
    name: "DKA Diagnostic Criteria",
    shortName: "DKA",
    category: "criteria",
    clinicalUse: "Diagnosis and severity classification of diabetic ketoacidosis",
    tags: ["DKA", "diabetes", "ketoacidosis", "glucose", "acidosis", "insulin"],
    scenarios: ["tox"],
    items: [
      { label: "ALL THREE required for diagnosis:", isHeader: true },
      { label: "Glucose > 250 mg/dL (may be lower in euglycemic DKA)" },
      { label: "pH < 7.30 OR bicarbonate < 18 mEq/L" },
      { label: "Positive urine or serum ketones" },
    ],
    interpretation: [
      { range: "pH 7.25-7.30 / HCO3 15-18", label: "Mild", action: "IVF, insulin drip, electrolyte replacement. Monitor q1-2h.", color: "#34D399" },
      { range: "pH 7.00-7.24 / HCO3 10-14", label: "Moderate", action: "Aggressive management. ICU consideration.", color: "#F59E0B" },
      { range: "pH < 7.00 / HCO3 < 10", label: "Severe", action: "ICU. Consider bicarb if pH < 6.9.", color: "#FF4444" },
    ],
    pearl: "Replace K+ BEFORE starting insulin. Do NOT give insulin if K+ < 3.5 mEq/L — drives dangerous hypokalemia.",
    source: "ADA DKA/HHS Consensus Statement 2009 (updated 2022)",
    hubLink: "ElectrolyteAcidBaseHub",
  },

  gcs: {
    id: "gcs",
    name: "Glasgow Coma Scale",
    shortName: "GCS",
    category: "scoring",
    clinicalUse: "Objective level of consciousness assessment",
    tags: ["GCS", "consciousness", "AMS", "TBI", "trauma", "intubation"],
    scenarios: ["trauma", "acls"],
    items: [
      { label: "EYE (E): Spontaneous 4 | Voice 3 | Pain 2 | None 1", isHeader: true },
      { label: "VERBAL (V): Oriented 5 | Confused 4 | Words 3 | Sounds 2 | None 1", isHeader: true },
      { label: "MOTOR (M): Commands 6 | Localizes 5 | Withdraws 4 | Flexion 3 | Extension 2 | None 1", isHeader: true },
    ],
    interpretation: [
      { range: "13-15", label: "Mild TBI", action: "Observe. CT if red flags (LOC, amnesia, vomiting, age > 65).", color: "#34D399" },
      { range: "9-12", label: "Moderate TBI", action: "CT head. Admit for monitoring.", color: "#F59E0B" },
      { range: "≤ 8", label: "Severe TBI", action: "Intubate — cannot protect airway. Neurosurgery consult urgently.", color: "#FF4444" },
    ],
    pearl: "GCS ≤ 8 = intubate. Motor score alone (M) is the strongest predictor of outcome in TBI.",
    source: "Teasdale & Jennett, Lancet 1974",
    hubLink: "AirwayHub",
  },

  hunt_hess: {
    id: "hunt_hess",
    name: "Hunt & Hess Scale",
    shortName: "Hunt & Hess",
    category: "scoring",
    clinicalUse: "Subarachnoid hemorrhage severity — surgical risk and prognosis",
    tags: ["SAH", "subarachnoid hemorrhage", "thunderclap headache", "aneurysm"],
    scenarios: ["stroke"],
    items: [
      { label: "I: Asymptomatic or mild headache / nuchal rigidity" },
      { label: "II: Moderate-severe headache, nuchal rigidity, no deficit except CN palsy" },
      { label: "III: Drowsy, confused, or mild focal deficit" },
      { label: "IV: Stupor, moderate-severe hemiparesis, early decerebrate posturing" },
      { label: "V: Deep coma, decerebrate rigidity, moribund" },
    ],
    interpretation: [
      { range: "I-II", label: "Good Grade", action: "Favorable outcome with treatment. Early surgery or coiling.", color: "#34D399" },
      { range: "III", label: "Intermediate", action: "Moderate risk. Timing of intervention variable.", color: "#F59E0B" },
      { range: "IV-V", label: "Poor Grade", action: "High mortality. Early goals-of-care discussion.", color: "#FF4444" },
    ],
    pearl: "Worst headache of life + thunderclap: LP or CTA if CT negative. 10-15% of SAH have normal initial CT.",
    source: "Hunt & Hess, J Neurosurg 1968",
    hubLink: "StrokeHub",
  },

  rule_of_nines: {
    id: "rule_of_nines",
    name: "Rule of Nines + Parkland Formula",
    shortName: "Burns / Parkland",
    category: "formula",
    clinicalUse: "Estimate TBSA burned and calculate fluid resuscitation volume",
    tags: ["burns", "TBSA", "Parkland", "fluid", "trauma", "LR"],
    scenarios: ["trauma"],
    items: [
      { label: "RULE OF NINES (adult TBSA):", isHeader: true },
      { label: "Head & neck: 9% | Each arm: 9% | Anterior trunk: 18% | Posterior trunk: 18% | Each leg: 18% | Perineum: 1%" },
      { label: "PARKLAND FORMULA:", isHeader: true },
      { label: "4 mL x weight (kg) x TBSA (%)" },
      { label: "Give 50% in first 8h from TIME OF BURN (not arrival)" },
      { label: "Give remaining 50% over next 16h" },
      { label: "Use Lactated Ringer's. Target UO 0.5-1 mL/kg/hr" },
    ],
    interpretation: [
      { range: "TBSA ≥ 20%", label: "Major Burn", action: "IV resuscitation + burn center transfer.", color: "#FF4444" },
      { range: "TBSA 10-20%", label: "Moderate", action: "IV access, monitoring, burn consult.", color: "#F59E0B" },
      { range: "TBSA < 10%", label: "Minor", action: "Outpatient management often appropriate.", color: "#34D399" },
    ],
    pearl: "Pediatric adjustment: head = 18%, each leg = 13%. Use Lund-Browder chart for children < 10.",
    source: "Baxter / Parkland formula 1968; ABA Practice Guidelines",
    hubLink: null,
  },

  chadsvasc: {
    id: "chadsvasc",
    name: "CHA₂DS₂-VASc Score",
    shortName: "CHA2DS2-VASc",
    category: "scoring",
    clinicalUse: "Annual stroke risk in non-valvular afib — guides anticoagulation",
    tags: ["afib", "atrial fibrillation", "stroke", "anticoagulation", "DOAC"],
    scenarios: ["acls"],
    items: [
      { label: "Congestive heart failure", points: 1 },
      { label: "Hypertension", points: 1 },
      { label: "Age ≥ 75", points: 2 },
      { label: "Diabetes mellitus", points: 1 },
      { label: "Stroke / TIA / thromboembolism history", points: 2 },
      { label: "Vascular disease (prior MI, PAD, aortic plaque)", points: 1 },
      { label: "Age 65-74", points: 1 },
      { label: "Sex category: Female", points: 1 },
    ],
    interpretation: [
      { range: "0 (M) / 1 (F)", label: "Low Risk", action: "Anticoagulation not recommended.", color: "#34D399" },
      { range: "1 (M)", label: "Low-Moderate", action: "Consider anticoagulation vs bleeding risk.", color: "#F59E0B" },
      { range: "≥ 2", label: "High Risk", action: "Anticoagulate — DOAC preferred over warfarin.", color: "#FF4444" },
    ],
    pearl: "Female sex alone (score = 1) does not warrant anticoagulation. It modifies risk only when other factors are present.",
    source: "Lip et al, Chest 2010; ESC AF Guidelines 2020",
    hubLink: "ECGHub",
  },

  alvarado: {
    id: "alvarado",
    name: "Alvarado Score",
    shortName: "MANTRELS",
    category: "scoring",
    clinicalUse: "Appendicitis probability — guide CT vs surgical consult",
    tags: ["appendicitis", "RLQ pain", "abdominal pain", "CT", "surgery"],
    scenarios: ["sepsis"],
    items: [
      { label: "Migration of pain to RLQ", points: 1 },
      { label: "Anorexia", points: 1 },
      { label: "Nausea / vomiting", points: 1 },
      { label: "Tenderness in RLQ", points: 2 },
      { label: "Rebound tenderness", points: 1 },
      { label: "Elevated temperature (> 37.3°C / 99.1°F)", points: 1 },
      { label: "Leukocytosis (WBC > 10,000)", points: 2 },
      { label: "Shift to left (neutrophilia)", points: 1 },
    ],
    interpretation: [
      { range: "1-4", label: "Low", action: "Appendicitis unlikely. Observe or discharge with precautions.", color: "#34D399" },
      { range: "5-6", label: "Equivocal", action: "CT or US abdomen. Surgical consult.", color: "#F59E0B" },
      { range: "7-10", label: "High", action: "Likely appendicitis. Surgical consult + OR preparation.", color: "#FF4444" },
    ],
    pearl: "Score ≥ 7 in males: consider direct OR without CT. CT recommended in women and children for DDx (ovarian pathology, Meckel).",
    source: "Alvarado, Ann Emerg Med 1986",
    hubLink: null,
  },
};