export const SPECIALTY_CONFIG = {
  "Emergency Medicine":      { icon: "🚨", color: "#ff5c6c", setting: "ED" },
  "Critical Care/ICU":       { icon: "🏥", color: "#ff8c42", setting: "ICU" },
  "Inpatient Medicine":      { icon: "🛏️",  color: "#4a90d9", setting: "Inpatient" },
  "Cardiology":              { icon: "❤️",  color: "#f472b6", setting: "Inpatient" },
  "Neurology":               { icon: "🧠",  color: "#9b6dff", setting: "Inpatient" },
  "Pulmonology":             { icon: "🫁",  color: "#22d3ee", setting: "Inpatient" },
  "Gastroenterology":        { icon: "🫀",  color: "#2ecc71", setting: "Inpatient" },
  "Nephrology":              { icon: "💧",  color: "#00d4bc", setting: "Inpatient" },
  "Endocrinology":           { icon: "🩸",  color: "#f5a623", setting: "Inpatient" },
  "Infectious Disease":      { icon: "🦠",  color: "#f0c040", setting: "Inpatient" },
  "Hematology/Oncology":     { icon: "🔬",  color: "#e879f9", setting: "Inpatient" },
  "Orthopedics":             { icon: "🦴",  color: "#94a3b8", setting: "Inpatient" },
  "Psychiatry":              { icon: "🧩",  color: "#818cf8", setting: "Inpatient" },
  "Outpatient/Primary Care": { icon: "🩺",  color: "#34d399", setting: "Outpatient" },
  "Pediatrics":              { icon: "👶",  color: "#60a5fa", setting: "Inpatient" },
  "Obstetrics & Gynecology": { icon: "🌸",  color: "#f9a8d4", setting: "Inpatient" },
  "Surgery":                 { icon: "🔪",  color: "#a78bfa", setting: "Inpatient" },
  "Procedures":              { icon: "💉",  color: "#6ee7b7", setting: "Procedures" },
};

export const NOTE_STATUSES = {
  draft:        { color: "#4a7299", label: "Draft" },
  ai_generated: { color: "#9b6dff", label: "AI Generated" },
  reviewed:     { color: "#f5a623", label: "Reviewed" },
  signed:       { color: "#2ecc71", label: "Signed" },
};

export const BUILTIN_TEMPLATES = [
  {
    id: "tpl-001", template_key: "ed-chest-pain",
    name: "ED — Chest Pain Evaluation",
    description: "ACS / STEMI workup, HEART score, risk stratification",
    specialty: "Emergency Medicine", setting: "ED", note_type: "Brief ED Note", icon: "❤️",
    tags: ["chest pain","ACS","STEMI","NSTEMI","HEART score","troponin"],
    fields: [
      { id:"cc",         label:"Chief Complaint",          type:"text",         required:true,  placeholder:"e.g. chest pain × 2 hours",                    group:"History",    width:"full" },
      { id:"hpi_onset",  label:"Onset",                   type:"text",         required:true,  placeholder:"When did it start?",                           group:"History",    width:"half" },
      { id:"hpi_char",   label:"Character",               type:"select",       required:true,  options:["pressure/squeezing","sharp/stabbing","burning","aching","tearing","pleuritic"], group:"History", width:"half" },
      { id:"hpi_rad",    label:"Radiation",               type:"multiselect",  required:false, options:["left arm","right arm","jaw","neck","back","shoulder","no radiation"],           group:"History", width:"half" },
      { id:"hpi_sev",    label:"Severity (0–10)",         type:"number",       required:true,  unit:"/10",                                                 group:"History",    width:"half" },
      { id:"hpi_assoc",  label:"Associated Symptoms",     type:"multiselect",  required:false, options:["diaphoresis","dyspnea","nausea/vomiting","syncope","palpitations","none"],      group:"History", width:"full" },
      { id:"hpi_exacer", label:"Exacerbating / Relieving",type:"textarea",     required:false, placeholder:"What makes it better or worse?",               group:"History",    width:"full" },
      { id:"pmh",        label:"Past Medical History",    type:"textarea",     required:true,  placeholder:"CAD, DM, HTN, prior MI, PCI, CABG…",           group:"Background", width:"full" },
      { id:"vitals",     label:"Vitals",                  type:"vitals_block", required:true,                                                              group:"Exam",       width:"full" },
      { id:"exam",       label:"Physical Exam",           type:"exam_checklist",required:true, options:["General: A&Ox3, NAD","Cardiovascular: RRR, no M/R/G","Pulmonary: CTAB, no W/R/R","Abdomen: Soft, NT/ND","Extremities: no edema"], group:"Exam", width:"full" },
      { id:"ekg",        label:"ECG Findings",            type:"textarea",     required:true,  placeholder:"NSR, rate 78, normal axis, no ST elevation…",  group:"Data",       width:"full" },
      { id:"trop1",      label:"Initial Troponin",        type:"number",       required:true,  unit:"ng/mL",                                               group:"Data",       width:"half" },
      { id:"trop2",      label:"3h Troponin (if done)",   type:"number",       required:false, unit:"ng/mL",                                               group:"Data",       width:"half" },
      { id:"cxr",        label:"CXR Findings",            type:"textarea",     required:false, placeholder:"No acute cardiopulmonary process…",            group:"Data",       width:"full" },
      { id:"heart_score",label:"HEART Score",             type:"number",       required:false, unit:"/10",                                                 group:"Risk",       width:"half" },
      { id:"impression", label:"Clinical Impression",     type:"select",       required:true,  options:["STEMI — activating cath lab","NSTEMI","Unstable angina","Stable angina / low-risk ACS","Non-cardiac chest pain","Aortic dissection concern","PE concern","Musculoskeletal","GERD/esophageal","Undifferentiated"], group:"Risk", width:"half" },
      { id:"disposition",label:"Disposition",             type:"select",       required:true,  options:["Admit — Cardiology","Admit — Telemetry","Cath lab activation","Observation × 6h","ED observation","Discharge with follow-up","Transfer"], group:"Plan", width:"full" },
      { id:"plan_free",  label:"Additional Plan Details", type:"textarea",     required:false, placeholder:"Medications given, further workup ordered…",   group:"Plan",       width:"full" },
    ],
    ai_prompt_template: "You are Notrya AI generating a professional Emergency Medicine chest pain evaluation note.\n\nPhysician-Provided Data:\n- Chief Complaint: {{cc}}\n- Onset: {{hpi_onset}}\n- Character: {{hpi_char}}\n- Radiation: {{hpi_rad}}\n- Severity: {{hpi_sev}}/10\n- Associated symptoms: {{hpi_assoc}}\n- Exacerbating/relieving: {{hpi_exacer}}\n- PMH: {{pmh}}\n- Vitals: {{vitals}}\n- Physical Exam: {{exam}}\n- ECG: {{ekg}}\n- Initial Troponin: {{trop1}} ng/mL; 3h Troponin: {{trop2}} ng/mL\n- CXR: {{cxr}}\n- HEART Score: {{heart_score}}/10\n- Clinical Impression: {{impression}}\n- Disposition: {{disposition}}\n- Additional plan: {{plan_free}}\n\nGenerate a complete, professional ED chest pain note with sections: Chief Complaint, HPI (narrative paragraph), PMH/PSH/Meds/Allergies, Review of Systems, Physical Examination, Data (ECG/Labs/Imaging), Risk Stratification (HEART score interpretation), Assessment & Plan (numbered), Disposition. Use professional medical language. Do not fabricate data not provided."
  },
  {
    id: "tpl-002", template_key: "ed-dyspnea",
    name: "ED — Dyspnea / Shortness of Breath",
    description: "Acute SOB workup: CHF vs PE vs pneumonia vs COPD exacerbation",
    specialty: "Emergency Medicine", setting: "ED", note_type: "Brief ED Note", icon: "🫁",
    tags: ["dyspnea","SOB","CHF","PE","pneumonia","COPD"],
    fields: [
      { id:"cc",        label:"Chief Complaint",       type:"text",         required:true,  placeholder:"SOB × 3 days, worsening",                    group:"History",    width:"full" },
      { id:"onset",     label:"Onset & Duration",      type:"text",         required:true,  placeholder:"Acute / subacute / chronic",                 group:"History",    width:"half" },
      { id:"severity",  label:"Severity",              type:"select",       required:true,  options:["Mild — SOB on exertion","Moderate — SOB at rest","Severe — unable to speak in full sentences","Critical — impending respiratory failure"], group:"History", width:"half" },
      { id:"associated",label:"Associated Symptoms",   type:"multiselect",  required:false, options:["cough","fever/chills","chest pain","orthopnea","PND","leg edema","hemoptysis","wheezing","pleuritic pain"], group:"History", width:"full" },
      { id:"pmh",       label:"Relevant PMH",          type:"textarea",     required:true,  placeholder:"CHF (EF%), COPD (GOLD stage), asthma…",      group:"Background", width:"full" },
      { id:"vitals",    label:"Vitals (include SpO₂)", type:"vitals_block", required:true,                                                            group:"Exam",       width:"full" },
      { id:"exam",      label:"Physical Exam",         type:"exam_checklist",required:true, options:["General: mild/moderate/severe distress","Respiratory: rate, effort, accessory muscle use","Pulmonary: CTAB / wheezing / crackles","Cardiovascular: regular/irregular, JVD","Extremities: pitting edema"], group:"Exam", width:"full" },
      { id:"cxr",       label:"CXR Findings",          type:"textarea",     required:true,  placeholder:"Describe infiltrate, effusion, cardiomegaly…",group:"Data",       width:"full" },
      { id:"bnp",       label:"BNP or NT-proBNP",      type:"number",       required:false, unit:"pg/mL",                                             group:"Data",       width:"half" },
      { id:"dimer",     label:"D-Dimer (if done)",     type:"number",       required:false, unit:"ng/mL",                                             group:"Data",       width:"half" },
      { id:"impression",label:"Primary Diagnosis",     type:"select",       required:true,  options:["Acute decompensated CHF","COPD exacerbation","Asthma exacerbation","Community-acquired pneumonia","Pulmonary embolism","Pneumothorax","Undifferentiated"], group:"Plan", width:"half" },
      { id:"disposition",label:"Disposition",          type:"select",       required:true,  options:["ICU","Step-down / monitored bed","Inpatient floor","ED observation","Discharge with follow-up"], group:"Plan", width:"half" },
      { id:"plan",      label:"Treatment Plan",        type:"textarea",     required:false, placeholder:"O₂ supplementation, medications given…",    group:"Plan",       width:"full" },
    ],
    ai_prompt_template: "Generate a complete professional ED dyspnea evaluation note. CC={{cc}}, Onset={{onset}}, Severity={{severity}}, Associated={{associated}}, PMH={{pmh}}, Vitals={{vitals}}, Exam={{exam}}, CXR={{cxr}}, BNP={{bnp}} pg/mL, D-Dimer={{dimer}}, Impression={{impression}}, Disposition={{disposition}}, Plan={{plan}}. Include: Chief Complaint, HPI narrative, PMH/Meds, Vitals & Exam, Data interpretation, Assessment (with differential), Plan (numbered), Disposition."
  },
  {
    id: "tpl-003", template_key: "ed-altered-ms",
    name: "ED — Altered Mental Status",
    description: "AMS workup: metabolic, toxic, structural, infectious, psychiatric",
    specialty: "Emergency Medicine", setting: "ED", note_type: "Brief ED Note", icon: "🧠",
    tags: ["AMS","altered mental status","confusion","delirium"],
    fields: [
      { id:"cc",         label:"Chief Complaint",         type:"text",         required:true,  placeholder:"Confusion, found unresponsive…", group:"History", width:"full" },
      { id:"historian",  label:"Historian",               type:"select",       required:true,  options:["Patient","Family member","EMS","Nursing home staff","Unknown"], group:"History", width:"half" },
      { id:"baseline",   label:"Baseline Mentation",      type:"select",       required:true,  options:["Alert and oriented at baseline","Mild cognitive impairment","Dementia (mild/moderate/severe)","Unknown baseline"], group:"History", width:"half" },
      { id:"timeline",   label:"Timeline of Change",      type:"text",         required:true,  placeholder:"Acute onset / gradual over days…", group:"History", width:"full" },
      { id:"pmh",        label:"PMH / Medications",       type:"textarea",     required:true,  placeholder:"Psych history, dementia, seizure disorder…", group:"Background", width:"full" },
      { id:"vitals",     label:"Vitals",                  type:"vitals_block", required:true,                                                    group:"Exam",       width:"full" },
      { id:"gcs",        label:"GCS",                     type:"text",         required:true,  placeholder:"E4 V4 M6 = 14",                    group:"Exam",       width:"half" },
      { id:"pupils",     label:"Pupils",                  type:"text",         required:true,  placeholder:"4mm bilaterally, equal and reactive", group:"Exam",     width:"half" },
      { id:"neuro_exam", label:"Neurological Exam",       type:"textarea",     required:true,  placeholder:"Focal deficits, cranial nerves, motor…", group:"Exam", width:"full" },
      { id:"glucose",    label:"POC Glucose",             type:"number",       required:true,  unit:"mg/dL",                                   group:"Data",       width:"half" },
      { id:"ct_head",    label:"CT Head (if done)",       type:"textarea",     required:false, placeholder:"No acute intracranial abnormality…", group:"Data",     width:"full" },
      { id:"etiology",   label:"Suspected Etiology",      type:"select",       required:true,  options:["Septic encephalopathy","Toxic/metabolic","Hypoglycemia","Stroke/CVA","Seizure (postictal)","Intracranial hemorrhage","CNS infection","Drug/alcohol intoxication","Undetermined"], group:"Plan", width:"half" },
      { id:"disposition",label:"Disposition",             type:"select",       required:true,  options:["ICU","Step-down","Inpatient Neurology","Inpatient Medicine","Psychiatry hold","Discharge with follow-up"], group:"Plan", width:"half" },
      { id:"plan",       label:"Management Plan",         type:"textarea",     required:false, placeholder:"Workup ordered, treatments given…", group:"Plan",       width:"full" },
    ],
    ai_prompt_template: "Generate a complete professional ED AMS evaluation note. CC={{cc}}, Historian={{historian}}, Baseline={{baseline}}, Timeline={{timeline}}, PMH={{pmh}}, Vitals={{vitals}}, GCS={{gcs}}, Pupils={{pupils}}, Neuro={{neuro_exam}}, Glucose={{glucose}} mg/dL, CT Head={{ct_head}}, Etiology={{etiology}}, Disposition={{disposition}}, Plan={{plan}}. Include CC, HPI narrative, PMH/Meds, Neuro Exam summary, Data interpretation, Assessment with differential, numbered Plan, Disposition."
  },
  {
    id: "tpl-004", template_key: "ed-abdominal-pain",
    name: "ED — Abdominal Pain",
    description: "Acute abdominal pain — surgical vs non-surgical evaluation",
    specialty: "Emergency Medicine", setting: "ED", note_type: "Brief ED Note", icon: "🔬",
    tags: ["abdominal pain","appendicitis","cholecystitis","pancreatitis"],
    fields: [
      { id:"cc",        label:"Chief Complaint",       type:"text",          required:true,  placeholder:"RLQ pain × 12 hours",         group:"History",    width:"full" },
      { id:"location",  label:"Location",              type:"multiselect",   required:true,  options:["RUQ","LUQ","RLQ","LLQ","Epigastric","Periumbilical","Diffuse","Suprapubic","Flank"], group:"History", width:"half" },
      { id:"onset",     label:"Onset",                 type:"select",        required:true,  options:["Acute — sudden onset","Gradual — over hours","Colicky — comes and goes","Post-prandial"], group:"History", width:"half" },
      { id:"sev",       label:"Severity",              type:"number",        required:true,  unit:"/10",                                group:"History",    width:"half" },
      { id:"assoc",     label:"Associated Symptoms",   type:"multiselect",   required:false, options:["nausea/vomiting","anorexia","fever/chills","diarrhea","constipation","hematochezia","dysuria","jaundice"], group:"History", width:"full" },
      { id:"pmh",       label:"Relevant PMH",          type:"textarea",      required:true,  placeholder:"Prior abdominal surgeries, IBD, gallstones…", group:"Background", width:"full" },
      { id:"vitals",    label:"Vitals",                type:"vitals_block",  required:true,                                             group:"Exam",       width:"full" },
      { id:"abd_exam",  label:"Abdominal Exam",        type:"textarea",      required:true,  placeholder:"Tenderness location, guarding, rigidity, rebound, Murphy's sign…", group:"Exam", width:"full" },
      { id:"imaging",   label:"Imaging Results",       type:"textarea",      required:false, placeholder:"CT abdomen/pelvis, US findings…", group:"Data",    width:"full" },
      { id:"impression",label:"Diagnosis",             type:"select",        required:true,  options:["Acute appendicitis","Acute cholecystitis","Pancreatitis","Bowel obstruction","Diverticulitis","Nephrolithiasis","Peptic ulcer disease","Undifferentiated"], group:"Plan", width:"half" },
      { id:"disposition",label:"Disposition",          type:"select",        required:true,  options:["OR — emergent surgery","Admit — Surgery","Admit — Medicine","Observation","Discharge with follow-up"], group:"Plan", width:"half" },
      { id:"plan",      label:"Management Plan",       type:"textarea",      required:false, placeholder:"IVF, NPO, analgesics, antibiotics…", group:"Plan", width:"full" },
    ],
    ai_prompt_template: "Generate a professional ED abdominal pain note. CC={{cc}}, Location={{location}}, Onset={{onset}}, Severity={{sev}}/10, Associated={{assoc}}, PMH={{pmh}}, Vitals={{vitals}}, Abdominal Exam={{abd_exam}}, Imaging={{imaging}}, Diagnosis={{impression}}, Disposition={{disposition}}, Plan={{plan}}. Write complete note with CC, HPI, PMH, Exam, Data, Assessment, Plan, Disposition."
  },
  {
    id: "tpl-008", template_key: "inpt-admission-hp",
    name: "Inpatient — Admission H&P",
    description: "Full history and physical for inpatient admission",
    specialty: "Inpatient Medicine", setting: "Inpatient", note_type: "H&P", icon: "🛏️",
    tags: ["admission","H&P","history and physical","inpatient"],
    fields: [
      { id:"cc",        label:"Chief Complaint",        type:"text",           required:true,  placeholder:"Reason for admission in patient's own words", group:"History",    width:"full" },
      { id:"hpi",       label:"HPI (key points)",       type:"textarea",       required:true,  placeholder:"Onset, character, severity, associated sx, timeline…", group:"History", width:"full" },
      { id:"pmh",       label:"Past Medical History",   type:"textarea",       required:true,  placeholder:"Numbered list of diagnoses with dates",       group:"Background", width:"full" },
      { id:"psh",       label:"Past Surgical History",  type:"textarea",       required:false, placeholder:"Surgeries with approximate dates",            group:"Background", width:"half" },
      { id:"social",    label:"Social History",         type:"textarea",       required:true,  placeholder:"Tobacco, alcohol, substances, occupation, living situation", group:"Background", width:"half" },
      { id:"vitals",    label:"Vitals",                 type:"vitals_block",   required:true,                                                             group:"Exam",       width:"full" },
      { id:"exam",      label:"Physical Examination",   type:"exam_checklist", required:true,  options:["General: appearance, A&Ox, NAD","HEENT: normocephalic, PERRL","Neck: no LAD, no JVD","Cardiovascular: RRR, S1/S2, no M/R/G","Pulmonary: clear bilaterally","Abdomen: soft, bowel sounds","Extremities: pulses, edema","Neuro: A&Ox, strength/sensation"], group:"Exam", width:"full" },
      { id:"labs",      label:"Admission Labs",         type:"labs_block",     required:false,                                                            group:"Data",       width:"full" },
      { id:"imaging",   label:"Imaging / Studies",      type:"textarea",       required:false, placeholder:"CXR, EKG, CT results…",                      group:"Data",       width:"full" },
      { id:"assessment",label:"Assessment (problem list)",type:"textarea",     required:true,  placeholder:"1. Primary diagnosis\n2. Secondary problem…", group:"Plan",       width:"full" },
      { id:"plan",      label:"Plan",                   type:"textarea",       required:true,  placeholder:"For each problem above, outline workup and management", group:"Plan", width:"full" },
    ],
    ai_prompt_template: "Generate a complete, professional inpatient admission History & Physical. CC={{cc}}, HPI={{hpi}}, PMH={{pmh}}, PSH={{psh}}, Social Hx={{social}}, Vitals={{vitals}}, Exam={{exam}}, Labs={{labs}}, Imaging={{imaging}}, Assessment={{assessment}}, Plan={{plan}}. Generate well-organized H&P. HPI should be a well-written narrative paragraph. Plan should be problem-numbered."
  },
  {
    id: "tpl-009", template_key: "inpt-progress-note",
    name: "Inpatient — Daily Progress Note (SOAP)",
    description: "Standard inpatient SOAP progress note",
    specialty: "Inpatient Medicine", setting: "Inpatient", note_type: "Progress Note", icon: "📝",
    tags: ["progress note","SOAP","inpatient","daily note","rounding"],
    fields: [
      { id:"subjective", label:"Subjective",             type:"textarea",   required:true,  placeholder:"How patient feels today, new complaints, overnight events…", group:"SOAP", width:"full" },
      { id:"vitals",     label:"Vital Signs",            type:"vitals_block",required:true,                                                                          group:"Objective", width:"full" },
      { id:"exam",       label:"Physical Exam (pertinent)",type:"textarea", required:true,  placeholder:"Focused exam for today — note changes from prior",           group:"Objective", width:"full" },
      { id:"labs",       label:"Labs / Data",            type:"labs_block", required:false,                                                                          group:"Objective", width:"full" },
      { id:"assessment", label:"Assessment",             type:"textarea",   required:true,  placeholder:"Overall clinical trajectory — improving/stable/worsening.",  group:"Assessment", width:"full" },
      { id:"plan",       label:"Plan (by problem)",      type:"textarea",   required:true,  placeholder:"1. Primary diagnosis — today's management\n2. Secondary…",   group:"Plan",       width:"full" },
      { id:"dispo",      label:"Anticipated Disposition",type:"select",     required:false, options:["Continue inpatient workup","Discharge planning initiated","Discharge today","Transfer to higher level of care","Pending labs/consults"], group:"Plan", width:"full" },
    ],
    ai_prompt_template: "Generate a professional inpatient daily SOAP progress note. Subjective={{subjective}}, Vitals={{vitals}}, Exam={{exam}}, Labs/Data={{labs}}, Assessment={{assessment}}, Plan={{plan}}, Anticipated Disposition={{dispo}}. Format as clean SOAP note. Assessment should include clinical trajectory. Plan numbered by problem."
  },
  {
    id: "tpl-010", template_key: "inpt-discharge-summary",
    name: "Inpatient — Discharge Summary",
    description: "Comprehensive discharge summary: hospital course, meds, follow-up",
    specialty: "Inpatient Medicine", setting: "Inpatient", note_type: "Discharge Summary", icon: "🚪",
    tags: ["discharge","discharge summary","hospital course","follow-up"],
    fields: [
      { id:"admit_date",     label:"Admission Date",          type:"date",     required:true,  group:"Header",   width:"half" },
      { id:"discharge_date", label:"Discharge Date",          type:"date",     required:true,  group:"Header",   width:"half" },
      { id:"admit_dx",       label:"Admitting Diagnosis",     type:"text",     required:true,  placeholder:"e.g. Chest pain, rule out ACS", group:"Header", width:"full" },
      { id:"principal_dx",   label:"Principal Discharge Dx",  type:"text",     required:true,  placeholder:"e.g. NSTEMI — Type 2",          group:"Header", width:"half" },
      { id:"secondary_dx",   label:"Secondary Diagnoses",     type:"textarea", required:false, placeholder:"1. HFrEF\n2. CKD Stage 3\n3. DM2…", group:"Header", width:"half" },
      { id:"hospital_course",label:"Hospital Course",         type:"textarea", required:true,  placeholder:"Brief narrative of hospitalization…", group:"Course", width:"full" },
      { id:"procedures",     label:"Procedures Performed",    type:"textarea", required:false, placeholder:"Cardiac catheterization, intubation, central line…", group:"Course", width:"full" },
      { id:"med_changes",    label:"Medication Changes",      type:"textarea", required:true,  placeholder:"NEW: Aspirin 81mg\nCHANGED: Metoprolol → 50mg BID\nSTOPPED: Ibuprofen", group:"Discharge", width:"full" },
      { id:"condition",      label:"Discharge Condition",     type:"select",   required:true,  options:["Good","Fair","Stable","Guarded","Serious"],  group:"Discharge", width:"half" },
      { id:"dispo_dest",     label:"Discharge Destination",   type:"select",   required:true,  options:["Home with self-care","Home with home health","Skilled nursing facility","Acute rehabilitation","Hospice — home","AMA"], group:"Discharge", width:"half" },
      { id:"followup",       label:"Follow-Up Instructions",  type:"textarea", required:true,  placeholder:"PCP in 7 days, Cardiology in 2 weeks…", group:"Discharge", width:"full" },
      { id:"precautions",    label:"Return Precautions",      type:"textarea", required:true,  placeholder:"Return to ED if: chest pain, severe SOB, fever > 101°F…", group:"Discharge", width:"full" },
    ],
    ai_prompt_template: "Generate a comprehensive, professional inpatient discharge summary. Admission={{admit_date}} — Discharge={{discharge_date}}, Admitting Dx={{admit_dx}}, Principal Dx={{principal_dx}}, Secondary Dx={{secondary_dx}}, Hospital Course={{hospital_course}}, Procedures={{procedures}}, Medication Changes={{med_changes}}, Condition={{condition}}, Destination={{dispo_dest}}, Follow-Up={{followup}}, Return Precautions={{precautions}}. Include all standard discharge summary sections. Medication changes should be clearly flagged as NEW/CHANGED/STOPPED."
  },
  {
    id: "tpl-012", template_key: "cardio-chf-progress",
    name: "Cardiology — CHF Daily Progress",
    description: "Heart failure inpatient progress: fluid status, BNP trending, GDMT",
    specialty: "Cardiology", setting: "Inpatient", note_type: "Progress Note", icon: "💧",
    tags: ["CHF","heart failure","GDMT","diuresis","BNP"],
    fields: [
      { id:"subjective",  label:"Subjective",              type:"textarea",    required:true,  placeholder:"SOB, orthopnea, PND, edema, fatigue…", group:"SOAP",      width:"full" },
      { id:"vitals",      label:"Vitals + Weight",         type:"vitals_block",required:true,                                                      group:"Objective", width:"full" },
      { id:"weight_chg",  label:"Weight Change",           type:"text",        required:true,  placeholder:"Today 82kg vs admission 87kg — net −5kg", group:"Objective", width:"half" },
      { id:"io_24h",      label:"24h I&O",                 type:"text",        required:true,  placeholder:"In: 1200mL / Out: 2800mL / Net: −1600mL", group:"Objective", width:"half" },
      { id:"bnp_today",   label:"BNP / NT-proBNP Today",  type:"number",      required:false, unit:"pg/mL",                                       group:"Objective", width:"half" },
      { id:"creat",       label:"Creatinine Today",        type:"number",      required:true,  unit:"mg/dL",                                       group:"Objective", width:"half" },
      { id:"k",           label:"Potassium Today",         type:"number",      required:true,  unit:"mEq/L",                                       group:"Objective", width:"half" },
      { id:"exam",        label:"Exam (volume status)",    type:"textarea",    required:true,  placeholder:"JVP, lung auscultation, edema grade, S3 gallop…", group:"Objective", width:"full" },
      { id:"diuretics",   label:"Current Diuretic Regimen",type:"textarea",    required:true,  placeholder:"Furosemide 80mg IV BID, response…",    group:"Plan",      width:"full" },
      { id:"gdmt",        label:"GDMT Status",             type:"textarea",    required:false, placeholder:"Beta-blocker: held / continuing\nACEi/ARB/ARNI: continuing\nSGLT2i: planned…", group:"Plan", width:"full" },
      { id:"assessment",  label:"Assessment",              type:"textarea",    required:true,  placeholder:"Volume status assessment, trajectory…", group:"Plan",      width:"full" },
      { id:"plan",        label:"Plan",                    type:"textarea",    required:true,  placeholder:"1. Volume overload — continue diuresis…\n2. HFrEF — GDMT optimization…", group:"Plan", width:"full" },
    ],
    ai_prompt_template: "Generate a professional Cardiology HF daily progress note. Subjective={{subjective}}, Vitals={{vitals}}, Weight={{weight_chg}}, 24h I&O={{io_24h}}, BNP today={{bnp_today}} pg/mL, Creatinine={{creat}} mg/dL, K⁺={{k}} mEq/L, Exam={{exam}}, Diuretics={{diuretics}}, GDMT={{gdmt}}, Assessment={{assessment}}, Plan={{plan}}. Write systematic HF progress note reviewing volume status, diuretic response, renal function, electrolytes, and GDMT optimization."
  },
  {
    id: "tpl-020", template_key: "endo-dka-progress",
    name: "Endocrinology — DKA Progress Note",
    description: "DKA daily progress: anion gap trending, insulin drip, K+ management",
    specialty: "Endocrinology", setting: "Inpatient", note_type: "Progress Note", icon: "🩸",
    tags: ["DKA","diabetic ketoacidosis","anion gap","insulin drip","potassium"],
    fields: [
      { id:"subjective",   label:"Subjective",                 type:"textarea",    required:true,  placeholder:"How patient feels, nausea improved, tolerating PO…", group:"SOAP",       width:"full" },
      { id:"vitals",       label:"Vitals",                     type:"vitals_block",required:true,                                                                    group:"Objective",  width:"full" },
      { id:"glucose",      label:"Current Glucose",            type:"number",      required:true,  unit:"mg/dL",                                                     group:"Objective",  width:"third" },
      { id:"ph",           label:"pH",                         type:"number",      required:true,                                                                    group:"Objective",  width:"third" },
      { id:"bicarb",       label:"Bicarbonate",                type:"number",      required:true,  unit:"mEq/L",                                                     group:"Objective",  width:"third" },
      { id:"ag",           label:"Anion Gap",                  type:"number",      required:true,  unit:"mEq/L",                                                     group:"Objective",  width:"third" },
      { id:"k",            label:"Potassium",                  type:"number",      required:true,  unit:"mEq/L",                                                     group:"Objective",  width:"third" },
      { id:"insulin_rate", label:"Insulin Drip Rate",          type:"text",        required:true,  placeholder:"0.1 units/kg/hr = X units/hr",                      group:"Objective",  width:"third" },
      { id:"resolution",   label:"DKA Resolution Criteria Met?",type:"select",     required:true,  options:["No — still in active DKA","Partially — AG closing but criteria not met","Yes — AG ≤ 12, pH > 7.3, bicarb > 18, tolerating PO — ready for transition"], group:"Assessment", width:"full" },
      { id:"assessment",   label:"Assessment",                 type:"textarea",    required:true,  placeholder:"DKA [mild/moderate/severe] — [improving/stable/worsening]…", group:"Assessment", width:"full" },
      { id:"plan",         label:"Plan",                       type:"textarea",    required:true,  placeholder:"1. DKA — continue insulin drip\n2. Potassium — replete\n3. Transition — SC insulin when criteria met…", group:"Plan", width:"full" },
    ],
    ai_prompt_template: "Generate a professional DKA progress note. Subjective={{subjective}}, Vitals={{vitals}}, Glucose={{glucose}} mg/dL, pH={{ph}}, Bicarb={{bicarb}} mEq/L, Anion Gap={{ag}} mEq/L, K⁺={{k}} mEq/L, Insulin Drip={{insulin_rate}}, Resolution={{resolution}}, Assessment={{assessment}}, Plan={{plan}}. Write systematic DKA progress note with clear trending of resolution criteria, potassium management, and transition planning."
  },
  {
    id: "tpl-024", template_key: "psych-eval",
    name: "Psychiatry — Inpatient Evaluation",
    description: "Full psychiatric evaluation: MSE, safety assessment, DSM-5 diagnosis",
    specialty: "Psychiatry", setting: "Inpatient", note_type: "Psychiatry Eval", icon: "🧩",
    tags: ["psychiatry","MSE","safety assessment","suicide risk","depression","psychosis"],
    fields: [
      { id:"reason",       label:"Reason for Consult",           type:"text",     required:true,  placeholder:"e.g. Suicidal ideation in setting of major depression", group:"Consult",  width:"full" },
      { id:"cc",           label:"Chief Complaint (patient's words)",type:"text", required:true,  placeholder:"In patient's own words",                              group:"History",  width:"full" },
      { id:"psych_hx",     label:"Psychiatric History",          type:"textarea", required:true,  placeholder:"Prior diagnoses, hospitalizations, outpatient treatment, prior SI/SA…", group:"History", width:"full" },
      { id:"substance",    label:"Substance Use History",        type:"textarea", required:true,  placeholder:"Alcohol, cannabis, opioids, stimulants, tobacco…",    group:"History",  width:"full" },
      { id:"mse_appearance",label:"MSE — Appearance / Behavior", type:"textarea", required:true,  placeholder:"Well-groomed / disheveled, cooperative / agitated…", group:"MSE",      width:"full" },
      { id:"mse_mood",     label:"MSE — Mood / Affect",          type:"textarea", required:true,  placeholder:"Mood: 'depressed'. Affect: flat/constricted/full/labile", group:"MSE",  width:"half" },
      { id:"mse_thought",  label:"MSE — Thought Process/Content",type:"textarea", required:true,  placeholder:"Linear/tangential; delusions, paranoia, SI, HI…",     group:"MSE",      width:"half" },
      { id:"mse_cognition",label:"MSE — Cognition / Insight",    type:"textarea", required:true,  placeholder:"Alert, oriented × 4, insight (poor/fair/good)…",      group:"MSE",      width:"full" },
      { id:"si",           label:"Suicidal Ideation",            type:"select",   required:true,  options:["No SI — denies","Passive SI — wishes to be dead, no plan","Active SI — with plan, no intent","Active SI — with plan and intent","SA — recent attempt"], group:"Risk", width:"half" },
      { id:"hi",           label:"Homicidal Ideation",           type:"select",   required:true,  options:["None","Passive — angry thoughts, no plan","Active — with plan","Active — with named target"], group:"Risk", width:"half" },
      { id:"risk_factors", label:"Risk / Protective Factors",    type:"textarea", required:true,  placeholder:"Risk: access to means, prior attempts, hopelessness\nProtective: family support, engaged in treatment…", group:"Risk", width:"full" },
      { id:"diagnosis",    label:"DSM-5 Diagnosis",              type:"textarea", required:true,  placeholder:"1. Major Depressive Disorder, Severe (F32.2)\n2. Alcohol Use Disorder (F10.20)", group:"Plan", width:"full" },
      { id:"recs",         label:"Treatment Recommendations",    type:"textarea", required:true,  placeholder:"1. Admit voluntary/involuntary\n2. Start SSRI\n3. Safety planning…", group:"Plan", width:"full" },
    ],
    ai_prompt_template: "Generate a professional psychiatric inpatient evaluation note. Reason={{reason}}, CC={{cc}}, Psych Hx={{psych_hx}}, Substance Use={{substance}}, MSE Appearance={{mse_appearance}}, MSE Mood/Affect={{mse_mood}}, MSE Thought={{mse_thought}}, MSE Cognition={{mse_cognition}}, SI={{si}}, HI={{hi}}, Risk/Protective={{risk_factors}}, Diagnosis={{diagnosis}}, Recs={{recs}}. Include clearly organized MSE, thorough risk assessment, and actionable recommendations."
  },
  {
    id: "tpl-025", template_key: "outpt-soap-followup",
    name: "Outpatient — SOAP Follow-Up Note",
    description: "Standard outpatient follow-up: chronic disease management, medication review",
    specialty: "Outpatient/Primary Care", setting: "Outpatient", note_type: "Outpatient SOAP", icon: "🩺",
    tags: ["follow-up","outpatient","SOAP","chronic disease","HTN","DM"],
    fields: [
      { id:"reason",     label:"Reason for Visit",          type:"text",           required:true,  placeholder:"e.g. HTN/DM follow-up, 3-month review",      group:"Visit",      width:"full" },
      { id:"subjective", label:"Subjective",                type:"textarea",       required:true,  placeholder:"Patient-reported symptoms, interval history since last visit…", group:"Visit", width:"full" },
      { id:"vitals",     label:"Vitals",                    type:"vitals_block",   required:true,                                                              group:"Objective",  width:"full" },
      { id:"exam",       label:"Physical Exam",             type:"exam_checklist", required:true,  options:["General: well-appearing, in NAD","Cardiovascular: RRR, no edema","Pulmonary: CTAB","Abdomen: soft, NT/ND"], group:"Objective", width:"full" },
      { id:"problems",   label:"Active Problems",           type:"textarea",       required:true,  placeholder:"1. HTN — BP at goal\n2. Type 2 DM — HbA1c 8.2%, not at goal…", group:"Assessment", width:"full" },
      { id:"plan",       label:"Plan",                      type:"textarea",       required:true,  placeholder:"Per problem above: counseling given, labs ordered, referrals…", group:"Plan",       width:"full" },
      { id:"followup",   label:"Return Interval",           type:"select",         required:true,  options:["1 week","2 weeks","1 month","3 months","6 months","As needed / PRN","Referring to specialist"], group:"Plan", width:"half" },
    ],
    ai_prompt_template: "Generate a professional outpatient SOAP follow-up note. Reason={{reason}}, Subjective={{subjective}}, Vitals={{vitals}}, Exam={{exam}}, Active Problems={{problems}}, Plan={{plan}}, Follow-Up={{followup}}. Assessment should address each active problem. Plan should be practical and evidence-based."
  },
  {
    id: "tpl-029", template_key: "procedure-central-line",
    name: "Procedure — Central Venous Catheter Placement",
    description: "CVC insertion note: indication, site, technique, complications, confirmation",
    specialty: "Procedures", setting: "ICU", note_type: "Procedure Note", icon: "💉",
    tags: ["central line","CVC","IJ","subclavian","ultrasound-guided"],
    fields: [
      { id:"indication", label:"Indication",         type:"multiselect", required:true,  options:["Vasopressor administration","Hemodynamic monitoring","Difficult peripheral access","Long-term antibiotic therapy","TPN administration","Dialysis"], group:"Procedure", width:"full" },
      { id:"site",       label:"Access Site",        type:"select",      required:true,  options:["Right internal jugular (RIJ)","Left internal jugular (LIJ)","Right subclavian (RSC)","Left subclavian (LSC)","Right femoral","Left femoral"], group:"Procedure", width:"half" },
      { id:"lumen",      label:"Catheter Type",      type:"select",      required:true,  options:["Triple-lumen CVC","Double-lumen CVC","Single-lumen CVC","7Fr introducer sheath","Dialysis catheter (non-tunneled)"], group:"Procedure", width:"half" },
      { id:"us_guided",  label:"Ultrasound Guidance",type:"boolean",     required:true,  default:true,                                             group:"Procedure", width:"half" },
      { id:"attempts",   label:"Number of Attempts", type:"number",      required:true,  default:1,                                                group:"Procedure", width:"half" },
      { id:"consent",    label:"Informed Consent",   type:"select",      required:true,  options:["Written consent obtained","Verbal consent (emergent)","Emergency — consent waived"], group:"Consent", width:"full" },
      { id:"technique",  label:"Technique",          type:"textarea",    required:true,  placeholder:"Patient positioned. Sterile prep and drape. US-guided visualization of [vein]. 18G needle used to cannulate…", group:"Procedure", width:"full" },
      { id:"complications",label:"Complications",    type:"multiselect", required:true,  options:["None — procedure successful","Arterial puncture (managed)","Hematoma","Pneumothorax","Hemothorax","Multiple attempts (> 3)"], group:"Complications", width:"full" },
      { id:"confirm",    label:"Confirmation",       type:"textarea",    required:true,  placeholder:"CXR obtained — catheter tip at [location], no pneumothorax. Catheter ready for use.", group:"Post-Procedure", width:"full" },
    ],
    ai_prompt_template: "Generate a formal procedure note for central venous catheter placement. Indication={{indication}}, Site={{site}}, Catheter={{lumen}}, US Guided={{us_guided}}, Attempts={{attempts}}, Consent={{consent}}, Technique={{technique}}, Complications={{complications}}, Confirmation={{confirm}}. Include all safety steps. Note should be medicolegally complete."
  },
  // ── NEW ED TEMPLATES ──────────────────────────────────────────────────────
  {
    id: "tpl-ed-stroke", template_key: "ed-stroke-cva",
    name: "ED — Stroke / CVA Evaluation",
    description: "Acute ischemic stroke workup, NIHSS, tPA / thrombectomy eligibility",
    specialty: "Emergency Medicine", setting: "ED", note_type: "Brief ED Note", icon: "🧠",
    tags: ["stroke","CVA","TIA","NIHSS","tPA","thrombectomy","facial droop","weakness"],
    fields: [
      { id:"cc",           label:"Chief Complaint",              type:"text",         required:true,  placeholder:"Left-sided weakness × 45 min",                    group:"History",    width:"full" },
      { id:"lkwt",         label:"Last Known Well Time",         type:"text",         required:true,  placeholder:"e.g. 08:30 AM — patient LKWT",                   group:"History",    width:"half" },
      { id:"symptoms",     label:"Neurological Symptoms",        type:"multiselect",  required:true,  options:["facial droop","arm weakness","leg weakness","speech difficulty (dysarthria/aphasia)","vision changes","diplopia","ataxia/gait instability","headache","altered consciousness","sensory loss"], group:"History", width:"full" },
      { id:"pmh",          label:"Relevant PMH / Meds",          type:"textarea",     required:true,  placeholder:"A-fib, HTN, DM, prior stroke/TIA, anticoagulants, antiplatelets…", group:"Background", width:"full" },
      { id:"vitals",       label:"Vitals",                       type:"vitals_block", required:true,                                                                  group:"Exam",       width:"full" },
      { id:"nihss",        label:"NIHSS Score",                  type:"number",       required:true,  unit:"/42",                                                     group:"Exam",       width:"half" },
      { id:"neuro_exam",   label:"Focused Neurological Exam",    type:"textarea",     required:true,  placeholder:"CN exam, motor (5/5 vs weakness), speech, gait if able…", group:"Exam", width:"full" },
      { id:"ct_head",      label:"Non-Contrast CT Head",         type:"textarea",     required:true,  placeholder:"No hemorrhage. No early ischemic changes. ASPECTS score…", group:"Data", width:"full" },
      { id:"cta",          label:"CTA Head/Neck (if done)",      type:"textarea",     required:false, placeholder:"LVO: MCA M1 occlusion / No LVO. Carotid stenosis…", group:"Data",   width:"full" },
      { id:"glucose_val",  label:"Blood Glucose",                type:"number",       required:true,  unit:"mg/dL",                                                   group:"Data",       width:"half" },
      { id:"inr",          label:"INR (if on warfarin)",         type:"number",       required:false,                                                                 group:"Data",       width:"half" },
      { id:"tpa_eligible", label:"tPA Eligibility",              type:"select",       required:true,  options:["Eligible — activating stroke team for tPA","Ineligible — beyond window (>4.5h)","Ineligible — hemorrhage on CT","Ineligible — INR >1.7 / on DOAC","Ineligible — BP uncontrolled","Ineligible — minor/improving","LVO present — thrombectomy indicated","TIA — no deficit at time of eval"], group:"Plan", width:"half" },
      { id:"impression",   label:"Clinical Impression",          type:"select",       required:true,  options:["Acute ischemic stroke — tPA given","Acute ischemic stroke — thrombectomy activated","Acute ischemic stroke — no intervention","TIA","Hemorrhagic stroke","Stroke mimic","Undetermined"], group:"Plan", width:"half" },
      { id:"plan",         label:"Management Plan",              type:"textarea",     required:false, placeholder:"BP management, tPA protocol, neurology consult, MRI order, antithrombotic plan…", group:"Plan", width:"full" },
    ],
    ai_prompt_template: "Generate a professional ED Acute Stroke evaluation note. CC={{cc}}, LKWT={{lkwt}}, Symptoms={{symptoms}}, PMH={{pmh}}, Vitals={{vitals}}, NIHSS={{nihss}}/42, Neuro Exam={{neuro_exam}}, CT Head={{ct_head}}, CTA={{cta}}, Glucose={{glucose_val}} mg/dL, INR={{inr}}, tPA Eligibility={{tpa_eligible}}, Impression={{impression}}, Plan={{plan}}. Include Time-is-Brain urgency language, clear documentation of LKWT and eligibility decision-making. Professional stroke note format."
  },
  {
    id: "tpl-ed-syncope", template_key: "ed-syncope",
    name: "ED — Syncope Evaluation",
    description: "Syncope risk stratification: cardiac vs vasovagal vs orthostatic, ROSE / SFSR score",
    specialty: "Emergency Medicine", setting: "ED", note_type: "Brief ED Note", icon: "⚡",
    tags: ["syncope","LOC","loss of consciousness","vasovagal","cardiac syncope","ROSE score"],
    fields: [
      { id:"cc",          label:"Chief Complaint",              type:"text",         required:true,  placeholder:"Brief loss of consciousness while standing…",       group:"History",    width:"full" },
      { id:"prodrome",    label:"Prodrome",                     type:"multiselect",  required:false, options:["none — no warning","nausea/diaphoresis (vasovagal)","chest pain or palpitations","lightheadedness","aura (seizure?)", "occurred with exertion"], group:"History", width:"full" },
      { id:"duration",    label:"Loss of Consciousness Duration",type:"text",        required:true,  placeholder:"Seconds / < 1 min / > 1 min",                       group:"History",    width:"half" },
      { id:"recovery",    label:"Recovery Pattern",             type:"select",       required:true,  options:["Immediate and complete","Prolonged confusion (postictal — seizure?)","Gradual — minutes","Incomplete at ED arrival"], group:"History", width:"half" },
      { id:"context",     label:"Context / Circumstances",      type:"multiselect",  required:true,  options:["prolonged standing","emotional trigger","Valsalva / straining","exertion","supine position (worrisome)","post-micturition","medication change","no clear trigger"], group:"History", width:"full" },
      { id:"pmh",         label:"PMH / Cardiac History",        type:"textarea",     required:true,  placeholder:"CAD, CHF, arrhythmia, structural heart disease, prior syncope…", group:"Background", width:"full" },
      { id:"vitals",      label:"Vitals (include orthostatics)", type:"vitals_block",required:true,                                                                    group:"Exam",       width:"full" },
      { id:"ortho",       label:"Orthostatic Vitals",           type:"text",         required:false, placeholder:"Supine: 130/80 HR 72 → Standing: 105/65 HR 100 (positive)", group:"Exam", width:"half" },
      { id:"exam",        label:"Physical Exam",                type:"exam_checklist",required:true, options:["General: no acute distress","Cardiovascular: rate/rhythm, murmurs","Neurological: A&Ox, focal deficits","Rectal: if GI bleed concern (occult blood / guaiac)"], group:"Exam", width:"full" },
      { id:"ekg",         label:"ECG",                          type:"textarea",     required:true,  placeholder:"NSR / AFib. QTc, Brugada pattern, pre-excitation, Wolff-Parkinson-White, complete heart block…", group:"Data", width:"full" },
      { id:"hgb",         label:"Hemoglobin",                   type:"number",       required:false, unit:"g/dL",                                                     group:"Data",       width:"half" },
      { id:"troponin",    label:"Troponin",                     type:"number",       required:false, unit:"ng/mL",                                                    group:"Data",       width:"half" },
      { id:"impression",  label:"Syncope Etiology",             type:"select",       required:true,  options:["Vasovagal / reflex syncope","Orthostatic hypotension","Cardiac arrhythmia","Structural cardiac cause","Neurological / seizure","GI bleed-related","Undetermined — high risk","Undetermined — low risk"], group:"Plan", width:"half" },
      { id:"disposition", label:"Disposition",                  type:"select",       required:true,  options:["Discharge — low risk, follow-up arranged","Admit — cardiac monitoring telemetry","Admit — cardiology evaluation","ED observation × 6h with monitoring","ICU"], group:"Plan", width:"half" },
      { id:"plan",        label:"Management Plan",              type:"textarea",     required:false, placeholder:"Orthostatic measures, Holter, Echo order, medication adjustments…", group:"Plan", width:"full" },
    ],
    ai_prompt_template: "Generate a professional ED syncope evaluation note. CC={{cc}}, Prodrome={{prodrome}}, Duration={{duration}}, Recovery={{recovery}}, Context={{context}}, PMH={{pmh}}, Vitals={{vitals}}, Orthostatics={{ortho}}, Exam={{exam}}, ECG={{ekg}}, Hgb={{hgb}} g/dL, Troponin={{troponin}} ng/mL, Etiology={{impression}}, Disposition={{disposition}}, Plan={{plan}}. Structured risk stratification. Clearly document features for and against cardiac etiology."
  },
  {
    id: "tpl-ed-sepsis", template_key: "ed-sepsis",
    name: "ED — Sepsis / Septic Shock",
    description: "Sepsis Hour-1 bundle documentation, source identification, risk stratification",
    specialty: "Emergency Medicine", setting: "ED", note_type: "Brief ED Note", icon: "🦠",
    tags: ["sepsis","septic shock","SIRS","qSOFA","hour-1 bundle","lactate","bacteremia"],
    fields: [
      { id:"cc",          label:"Chief Complaint",              type:"text",         required:true,  placeholder:"Fever, hypotension, altered mentation…",             group:"History",    width:"full" },
      { id:"source",      label:"Suspected Infection Source",   type:"select",       required:true,  options:["Pulmonary (pneumonia)","Urinary tract (pyelonephritis)","Intra-abdominal","Skin/soft tissue (SSTI/cellulitis)","Bloodstream / line infection","CNS","Endovascular","Unknown source"], group:"History", width:"half" },
      { id:"timeline",    label:"Timeline of Illness",          type:"text",         required:true,  placeholder:"2 days of fever, progressive hypotension…",          group:"History",    width:"half" },
      { id:"pmh",         label:"PMH / Immunosuppression",      type:"textarea",     required:true,  placeholder:"Diabetes, cirrhosis, malignancy, steroids, transplant, ESRD…", group:"Background", width:"full" },
      { id:"vitals",      label:"Vitals (full set)",            type:"vitals_block", required:true,                                                                    group:"Exam",       width:"full" },
      { id:"qsofa",       label:"qSOFA Score",                  type:"number",       required:true,  unit:"/3",                                                        group:"Exam",       width:"half" },
      { id:"exam",        label:"Physical Exam",                type:"exam_checklist",required:true, options:["General: toxic appearing / obtunded","Cardiovascular: muffled tachycardia, warm/mottled extremities","Pulmonary: crackles / diffuse infiltrates","Abdomen: tenderness (source)","Skin: petechiae, purpura, wound finding","Neuro: confusion / GCS"], group:"Exam", width:"full" },
      { id:"lactate",     label:"Initial Lactate",              type:"number",       required:true,  unit:"mmol/L",                                                    group:"Data",       width:"third" },
      { id:"lactate2",    label:"Repeat Lactate (2h)",          type:"number",       required:false, unit:"mmol/L",                                                    group:"Data",       width:"third" },
      { id:"wbc",         label:"WBC",                          type:"number",       required:true,  unit:"×10³/µL",                                                   group:"Data",       width:"third" },
      { id:"cultures",    label:"Cultures Obtained",            type:"multiselect",  required:true,  options:["Blood ×2 (peripheral)","Blood ×1 (from line)","Urine culture","Sputum culture","Wound culture","LP (CSF)","No cultures — emergent antibiotics given"], group:"Data", width:"full" },
      { id:"abx",         label:"Antibiotics Given",            type:"textarea",     required:true,  placeholder:"Pip-Tazo 4.5g IV + Vancomycin 25 mg/kg IV at 14:35…", group:"Plan",      width:"full" },
      { id:"fluids",      label:"Fluid Resuscitation",          type:"textarea",     required:true,  placeholder:"LR 30 mL/kg = 2100 mL over 2h started 14:30…",       group:"Plan",      width:"full" },
      { id:"pressors",    label:"Vasopressors",                 type:"select",       required:true,  options:["Not required — responding to fluids","Norepinephrine started (dose)","Vasopressin added","Epinephrine added","Multiple agents"], group:"Plan", width:"half" },
      { id:"impression",  label:"Clinical Impression",          type:"select",       required:true,  options:["Sepsis (without shock)","Septic shock — on vasopressors","Severe sepsis — lactate > 4","Sepsis suspected — workup ongoing","SIRS — non-infectious"], group:"Plan", width:"half" },
      { id:"disposition", label:"Disposition",                  type:"select",       required:true,  options:["ICU — septic shock","Step-down / monitored bed","Medical floor","ED observation"], group:"Plan", width:"half" },
    ],
    ai_prompt_template: "Generate a professional ED Sepsis/Septic Shock evaluation note with Hour-1 bundle documentation. CC={{cc}}, Source={{source}}, Timeline={{timeline}}, PMH={{pmh}}, Vitals={{vitals}}, qSOFA={{qsofa}}/3, Exam={{exam}}, Lactate={{lactate}} mmol/L (2h={{lactate2}}), WBC={{wbc}}, Cultures={{cultures}}, Antibiotics={{abx}}, Fluids={{fluids}}, Vasopressors={{pressors}}, Impression={{impression}}, Disposition={{disposition}}. Include SSC Hour-1 bundle checklist documentation. Professional and medicolegally complete."
  },
  {
    id: "tpl-ed-headache", template_key: "ed-headache",
    name: "ED — Headache Evaluation",
    description: "Thunderclap, migraine, meningitis, subarachnoid hemorrhage workup",
    specialty: "Emergency Medicine", setting: "ED", note_type: "Brief ED Note", icon: "🤕",
    tags: ["headache","thunderclap","migraine","SAH","meningitis","LP","subarachnoid"],
    fields: [
      { id:"cc",          label:"Chief Complaint",              type:"text",         required:true,  placeholder:"Worst headache of life × 2 hours",                   group:"History",    width:"full" },
      { id:"onset",       label:"Onset Pattern",                type:"select",       required:true,  options:["Thunderclap — max intensity within seconds","Rapid — max within minutes","Gradual — over hours","Chronic daily headache — change in character","Recurrent — typical migraine pattern"], group:"History", width:"half" },
      { id:"location",    label:"Location",                     type:"multiselect",  required:true,  options:["frontal","temporal (bilateral)","temporal (unilateral)","occipital","retro-orbital","diffuse/holocranial","neck/occipital"], group:"History", width:"half" },
      { id:"sev",         label:"Severity",                     type:"number",       required:true,  unit:"/10",                                                       group:"History",    width:"half" },
      { id:"assoc",       label:"Associated Symptoms",          type:"multiselect",  required:false, options:["nausea/vomiting","photophobia","phonophobia","neck stiffness","fever","focal neuro symptoms","vision changes","aura","syncope / LOC"], group:"History", width:"full" },
      { id:"prior",       label:"Prior Headache History",       type:"select",       required:true,  options:["No prior headache history (new onset — high risk)","Known migraineur — typical headache","Known migraineur — atypical features","Chronic daily headache — worsening","Cluster headache history"], group:"Background", width:"half" },
      { id:"pmh",         label:"PMH / Medications",            type:"textarea",     required:true,  placeholder:"HIV, immunocompromise, anticoagulants, prior aneurysm…", group:"Background", width:"half" },
      { id:"vitals",      label:"Vitals",                       type:"vitals_block", required:true,                                                                    group:"Exam",       width:"full" },
      { id:"neuro",       label:"Neurological Exam",            type:"textarea",     required:true,  placeholder:"A&Ox4, pupils equal/reactive, CN II-XII intact, no focal deficits, Kernig/Brudzinski…", group:"Exam", width:"full" },
      { id:"ct_head",     label:"CT Head (non-contrast)",       type:"textarea",     required:true,  placeholder:"No hemorrhage, no midline shift, normal sulcal pattern…", group:"Data",   width:"full" },
      { id:"lp_done",     label:"Lumbar Puncture Performed?",   type:"select",       required:true,  options:["Yes — results below","No — CT negative + low pretest prob, clinical LKWT > 6h","No — patient refused","No — CT positive (deferred)"], group:"Data", width:"half" },
      { id:"lp_results",  label:"LP Results (if done)",         type:"textarea",     required:false, placeholder:"OP: 18 cmH2O. Color: clear. WBC: 2. RBC: 0 (tube 4: 0). Xanthochromia: absent.", group:"Data", width:"full" },
      { id:"impression",  label:"Diagnosis",                    type:"select",       required:true,  options:["Subarachnoid hemorrhage — CT+ or LP+","Meningitis / Encephalitis","Intracranial hypertension","Migraine — typical","Migraine with aura","Cluster headache","Tension-type headache","Thunderclap — SAH excluded","Undetermined"], group:"Plan", width:"half" },
      { id:"disposition", label:"Disposition",                  type:"select",       required:true,  options:["Neurosurgery/ICU — SAH or emergency","Admit — Neurology","Admit — Medicine","Observation × 6h","Discharge — treated, follow-up"], group:"Plan", width:"half" },
      { id:"plan",        label:"Treatment Plan",               type:"textarea",     required:false, placeholder:"Medications given, imaging ordered, neurology consult…", group:"Plan",   width:"full" },
    ],
    ai_prompt_template: "Generate a professional ED headache evaluation note. CC={{cc}}, Onset={{onset}}, Location={{location}}, Severity={{sev}}/10, Associated={{assoc}}, Prior Hx={{prior}}, PMH={{pmh}}, Vitals={{vitals}}, Neuro={{neuro}}, CT Head={{ct_head}}, LP={{lp_done}}, LP Results={{lp_results}}, Diagnosis={{impression}}, Disposition={{disposition}}, Plan={{plan}}. Clearly document SAH risk stratification and LP decision-making. Include Ottawa SAH Rule / Ottawa Score documentation."
  },
  {
    id: "tpl-ed-trauma", template_key: "ed-trauma",
    name: "ED — Trauma Evaluation",
    description: "Mechanism, primary/secondary survey, FAST, injuries identified, trauma activation",
    specialty: "Emergency Medicine", setting: "ED", note_type: "Brief ED Note", icon: "🩹",
    tags: ["trauma","MVC","fall","assault","FAST exam","primary survey","secondary survey"],
    fields: [
      { id:"mechanism",   label:"Mechanism of Injury",          type:"text",         required:true,  placeholder:"MVC at 50 mph, unrestrained driver; 10-ft fall from ladder…", group:"History", width:"full" },
      { id:"ems",         label:"EMS / Pre-Hospital Report",    type:"textarea",     required:false, placeholder:"GCS at scene, interventions, vitals en route…",       group:"History",    width:"full" },
      { id:"pmh",         label:"PMH / Anticoagulants",         type:"textarea",     required:true,  placeholder:"Anticoagulants (warfarin, apixaban), prior surgeries…", group:"Background", width:"full" },
      { id:"vitals",      label:"Arrival Vitals",               type:"vitals_block", required:true,                                                                    group:"Primary Survey", width:"full" },
      { id:"primary",     label:"Primary Survey (ABCDE)",       type:"textarea",     required:true,  placeholder:"A: airway patent. B: equal breath sounds bilaterally. C: GCS 15, HR 98, 2 IVs placed. D: A&Ox4, pupils 3mm equal. E: Foley placed.", group:"Primary Survey", width:"full" },
      { id:"fast",        label:"FAST Exam",                    type:"select",       required:true,  options:["Negative — no free fluid in all 4 windows","Positive — free fluid pericardial window","Positive — free fluid RUQ","Positive — free fluid LUQ","Positive — free fluid pelvic window","Indeterminate / technically difficult","Not performed"], group:"Primary Survey", width:"half" },
      { id:"gcs_score",   label:"GCS",                          type:"text",         required:true,  placeholder:"E4 V5 M6 = 15",                                     group:"Primary Survey", width:"half" },
      { id:"secondary",   label:"Secondary Survey",             type:"textarea",     required:true,  placeholder:"Head: no laceration, PERRL. Neck: C-collar in place, no midline tenderness. Chest: symmetric expansion. Abdomen: mild tenderness. Pelvis: stable. Extremities: deformity R femur…", group:"Secondary Survey", width:"full" },
      { id:"imaging",     label:"Imaging Results",              type:"textarea",     required:false, placeholder:"CT Head: no hemorrhage. CT C-spine: no fracture. CT Chest/Abd/Pelvis: pneumothorax, splenic laceration (grade II)…", group:"Data", width:"full" },
      { id:"injuries",    label:"Injuries Identified",          type:"textarea",     required:true,  placeholder:"1. Right rib fractures 4–6\n2. Grade II splenic laceration\n3. Right tibial fracture", group:"Plan", width:"full" },
      { id:"impression",  label:"Severity",                     type:"select",       required:true,  options:["Major trauma — trauma team activated","Moderate trauma — surgical consult","Minor trauma — no surgical intervention","Trauma — clearance complete"], group:"Plan", width:"half" },
      { id:"disposition", label:"Disposition",                  type:"select",       required:true,  options:["OR — emergent","Trauma ICU","Surgery floor","Observation","Discharge with ortho/follow-up"], group:"Plan", width:"half" },
      { id:"plan",        label:"Management Plan",              type:"textarea",     required:false, placeholder:"Trauma surgery, ortho, neurosurgery consults; blood products; imaging…", group:"Plan", width:"full" },
    ],
    ai_prompt_template: "Generate a professional ED Trauma evaluation note. Mechanism={{mechanism}}, EMS={{ems}}, PMH={{pmh}}, Vitals={{vitals}}, Primary Survey={{primary}}, FAST={{fast}}, GCS={{gcs_score}}, Secondary Survey={{secondary}}, Imaging={{imaging}}, Injuries={{injuries}}, Severity={{impression}}, Disposition={{disposition}}, Plan={{plan}}. Organized in standard trauma note format: mechanism, primary survey, secondary survey, data, injuries, plan."
  },
  {
    id: "tpl-ed-uti-flank", template_key: "ed-uti-flank",
    name: "ED — UTI / Flank Pain / Nephrolithiasis",
    description: "UTI, pyelonephritis, renal colic, urinary obstruction evaluation",
    specialty: "Emergency Medicine", setting: "ED", note_type: "Brief ED Note", icon: "🫘",
    tags: ["UTI","urinary tract infection","pyelonephritis","kidney stone","flank pain","nephrolithiasis","renal colic"],
    fields: [
      { id:"cc",          label:"Chief Complaint",              type:"text",         required:true,  placeholder:"Right flank pain × 4 hours, hematuria",              group:"History",    width:"full" },
      { id:"symptoms",    label:"Urinary Symptoms",             type:"multiselect",  required:true,  options:["dysuria","urinary frequency","urgency","hematuria (gross)","cloudy urine","foul-smelling urine","flank pain","suprapubic pain","fever/chills","nausea/vomiting"], group:"History", width:"full" },
      { id:"pain_char",   label:"Pain Character (if flank pain)",type:"select",      required:false, options:["Colicky — waves every few minutes (stone)","Constant — dull ache","Severe constant — obstruction concern","Mild — discomfort only"], group:"History", width:"half" },
      { id:"pmh",         label:"Relevant PMH",                 type:"textarea",     required:true,  placeholder:"Prior UTIs, kidney stones, DM, immunosuppression, pregnancy status (LMP)…", group:"Background", width:"half" },
      { id:"vitals",      label:"Vitals",                       type:"vitals_block", required:true,                                                                    group:"Exam",       width:"full" },
      { id:"exam",        label:"Physical Exam",                type:"exam_checklist",required:true, options:["Abdomen: suprapubic tenderness, peritoneal signs","Flank: CVA tenderness (R/L/bilateral)","Pelvic exam (if indicated in female)","Rectal exam (if prostatitis concern)"], group:"Exam", width:"full" },
      { id:"ua",          label:"Urinalysis",                   type:"textarea",     required:true,  placeholder:"WBC 50-100 HPF, bacteria +, nitrite +, leukocyte esterase +, RBC 10-25…", group:"Data", width:"full" },
      { id:"ucx",         label:"Urine Culture Sent?",          type:"select",       required:true,  options:["Yes — culture sent","No — urinalysis sufficient for uncomplicated UTI","Not indicated"], group:"Data", width:"half" },
      { id:"ct_kub",      label:"CT KUB / Renal US (if done)",  type:"textarea",     required:false, placeholder:"5mm distal ureter stone with mild proximal hydroureteronephrosis…", group:"Data", width:"full" },
      { id:"impression",  label:"Diagnosis",                    type:"select",       required:true,  options:["Uncomplicated UTI (cystitis)","Complicated UTI — febrile / systemic","Pyelonephritis","Nephrolithiasis — uncomplicated","Nephrolithiasis — obstructing / urosepsis","Urinary retention","Epididymo-orchitis","Prostatitis","Undetermined"], group:"Plan", width:"half" },
      { id:"disposition", label:"Disposition",                  type:"select",       required:true,  options:["Discharge — oral antibiotics","Admit — IV antibiotics","Urology consult — emergent (obstructing stone + infection)","ED observation"], group:"Plan", width:"half" },
      { id:"plan",        label:"Treatment Plan",               type:"textarea",     required:false, placeholder:"Antibiotics selected, IV fluids, pain management, urology referral…", group:"Plan", width:"full" },
    ],
    ai_prompt_template: "Generate a professional ED UTI/flank pain evaluation note. CC={{cc}}, Symptoms={{symptoms}}, Pain={{pain_char}}, PMH={{pmh}}, Vitals={{vitals}}, Exam={{exam}}, UA={{ua}}, Culture={{ucx}}, Imaging={{ct_kub}}, Diagnosis={{impression}}, Disposition={{disposition}}, Plan={{plan}}. Distinguish between uncomplicated/complicated UTI, pyelonephritis, and nephrolithiasis. Include antibiotic selection rationale."
  },
  {
    id: "tpl-ed-peds-fever", template_key: "ed-peds-fever",
    name: "ED — Pediatric Fever Evaluation",
    description: "Febrile child workup: SBI risk, meningitis, Rochester/Philadelphia criteria, disposition",
    specialty: "Emergency Medicine", setting: "ED", note_type: "Brief ED Note", icon: "🌡️",
    tags: ["pediatric fever","febrile","meningitis","SBI","sepsis","infants","rash","petechiae","FOCAL"],
    fields: [
      { id:"cc",          label:"Chief Complaint",              type:"text",         required:true,  placeholder:"Fever 103.5°F × 2 days, 18-month-old",               group:"History",    width:"full" },
      { id:"age",         label:"Age",                          type:"text",         required:true,  placeholder:"e.g. 18 months / 6 weeks",                           group:"History",    width:"third" },
      { id:"weight",      label:"Weight",                       type:"number",       required:true,  unit:"kg",                                                        group:"History",    width:"third" },
      { id:"temp_peak",   label:"Peak Temperature",             type:"number",       required:true,  unit:"°F",                                                        group:"History",    width:"third" },
      { id:"duration",    label:"Duration of Fever",            type:"text",         required:true,  placeholder:"1 day / 3 days / 5 days",                            group:"History",    width:"half" },
      { id:"symptoms",    label:"Associated Symptoms",          type:"multiselect",  required:true,  options:["rhinorrhea / URI symptoms","cough","ear pain / tugging","throat pain","vomiting / diarrhea","rash (describe below)","decreased activity / lethargy","decreased PO intake","dysuria","neck stiffness","photophobia"], group:"History", width:"full" },
      { id:"rash",        label:"Rash Description (if present)",type:"text",         required:false, placeholder:"petechial, maculopapular, blanching…",               group:"History",    width:"half" },
      { id:"immunized",   label:"Immunization Status",          type:"select",       required:true,  options:["Up to date","Behind schedule","Unknown","Not vaccinated — parental refusal"], group:"Background", width:"half" },
      { id:"pmh",         label:"PMH",                          type:"textarea",     required:true,  placeholder:"Premature birth, sickle cell, prior hospitalizations, recent sick contacts…", group:"Background", width:"full" },
      { id:"vitals",      label:"Vitals (including SpO₂)",      type:"vitals_block", required:true,                                                                    group:"Exam",       width:"full" },
      { id:"exam",        label:"Physical Exam",                type:"exam_checklist",required:true, options:["General: well-appearing vs ill-appearing / toxic","Fontanelle: flat / bulging (if ≤18 mo)","HEENT: TM findings, pharynx, neck rigidity","Respiratory: clear / crackles","Skin: rash distribution, petechiae","Abdomen: soft, organomegaly"], group:"Exam", width:"full" },
      { id:"wbc",         label:"WBC (if obtained)",            type:"number",       required:false, unit:"×10³/µL",                                                   group:"Data",       width:"third" },
      { id:"anc",         label:"ANC",                          type:"number",       required:false, unit:"×10³/µL",                                                   group:"Data",       width:"third" },
      { id:"crp",         label:"CRP",                          type:"number",       required:false, unit:"mg/L",                                                      group:"Data",       width:"third" },
      { id:"ua",          label:"Urinalysis",                   type:"text",         required:false, placeholder:"WBC, bacteria, leukocyte esterase, nitrite",         group:"Data",       width:"half" },
      { id:"cxr",         label:"CXR (if done)",                type:"text",         required:false, placeholder:"No infiltrate / RLL infiltrate",                     group:"Data",       width:"half" },
      { id:"impression",  label:"Diagnosis",                    type:"select",       required:true,  options:["Viral URI — low SBI risk","Otitis media","Pneumonia — bacterial","UTI — febrile","Serious bacterial infection — bacteremia/sepsis","Meningitis concern — LP indicated","Rash — viral exanthem","Rash — petechial — serious concern","Undetermined"], group:"Plan", width:"half" },
      { id:"disposition", label:"Disposition",                  type:"select",       required:true,  options:["Discharge — well-appearing, return precautions given","Admit — IV antibiotics","PICU — sepsis / meningitis","Observation × 12–24h","Follow-up with PCP in 24–48h"], group:"Plan", width:"half" },
      { id:"plan",        label:"Management Plan",              type:"textarea",     required:false, placeholder:"Antipyretics, hydration, antibiotics if indicated, return precautions…", group:"Plan", width:"full" },
    ],
    ai_prompt_template: "Generate a professional ED Pediatric Fever evaluation note. CC={{cc}}, Age={{age}}, Weight={{weight}} kg, Peak Temp={{temp_peak}}°F, Duration={{duration}}, Symptoms={{symptoms}}, Rash={{rash}}, Immunizations={{immunized}}, PMH={{pmh}}, Vitals={{vitals}}, Exam={{exam}}, WBC={{wbc}}, ANC={{anc}}, CRP={{crp}}, UA={{ua}}, CXR={{cxr}}, Diagnosis={{impression}}, Disposition={{disposition}}, Plan={{plan}}. Apply age-appropriate SBI risk criteria (Rochester for <2mo, FOCAL/PECARN for older). Note well-appearing vs ill-appearing status prominently."
  },
  {
    id: "tpl-ed-overdose", template_key: "ed-overdose-tox",
    name: "ED — Overdose / Toxicology",
    description: "Intentional/unintentional overdose: toxidrome identification, NAC, naloxone, decontamination",
    specialty: "Emergency Medicine", setting: "ED", note_type: "Brief ED Note", icon: "☠️",
    tags: ["overdose","toxicology","toxidrome","naloxone","NAC","acetaminophen","opioid overdose","suicidal ingestion"],
    fields: [
      { id:"cc",          label:"Chief Complaint",              type:"text",         required:true,  placeholder:"Found unresponsive, empty pill bottles at scene",    group:"History",    width:"full" },
      { id:"intent",      label:"Intent",                       type:"select",       required:true,  options:["Intentional (suicidal)","Intentional (recreational)","Unintentional / accidental","Unknown"], group:"History", width:"half" },
      { id:"substance",   label:"Substance(s) Ingested",        type:"textarea",     required:true,  placeholder:"Acetaminophen 10g (20 × 500mg), last dose 3h ago; EtOH unknown amount", group:"History", width:"full" },
      { id:"time_ingestion",label:"Time of Ingestion",          type:"text",         required:true,  placeholder:"e.g. 3 hours ago (ingestion at 11:00 PM)",          group:"History",    width:"half" },
      { id:"pmh",         label:"PMH / Psych History",          type:"textarea",     required:true,  placeholder:"Prior suicide attempts, psych diagnoses, chronic meds…", group:"Background", width:"full" },
      { id:"vitals",      label:"Vitals",                       type:"vitals_block", required:true,                                                                    group:"Exam",       width:"full" },
      { id:"toxidrome",   label:"Toxidrome",                    type:"select",       required:true,  options:["Opioid: miosis, respiratory depression, sedation","Sympathomimetic: tachycardia, hypertension, agitation, mydriasis","Anticholinergic: dry/flushed, urinary retention, delirium, tachycardia","Cholinergic: SLUDGE/DUMBELS — salivation, lacrimation","Serotonin syndrome: hyperthermia, clonus, diaphoresis","Sedative-hypnotic: CNS/respiratory depression","Acetaminophen: may appear well early","No clear toxidrome"], group:"Exam", width:"half" },
      { id:"exam",        label:"Physical Exam",                type:"exam_checklist",required:true, options:["General: LOC/GCS, skin color/temperature","HEENT: pupils (miosis/mydriasis), nystagmus","Respiratory: rate, quality, need for intubation","Cardiovascular: rate, rhythm, QTc concern","Neurological: agitation, clonus, tremor"], group:"Exam", width:"full" },
      { id:"etoh",        label:"Blood EtOH Level",             type:"number",       required:false, unit:"mg/dL",                                                     group:"Data",       width:"third" },
      { id:"apap",        label:"Acetaminophen Level",          type:"number",       required:true,  unit:"mcg/mL",                                                    group:"Data",       width:"third" },
      { id:"asa",         label:"Aspirin Level",                type:"number",       required:false, unit:"mg/dL",                                                     group:"Data",       width:"third" },
      { id:"ekg",         label:"ECG (QTc, QRS width)",         type:"textarea",     required:true,  placeholder:"NSR, QTc 480 ms, QRS 88 ms, no Brugada pattern…",  group:"Data",       width:"full" },
      { id:"treatment",   label:"Treatment Given",              type:"multiselect",  required:true,  options:["Activated charcoal 1g/kg PO/NG","Naloxone IV/IM/IN","N-Acetylcysteine (IV Rumack-Matthew protocol)","Flumazenil (benzodiazepine reversal)","Sodium bicarbonate (TCA/wide QRS)","Physostigmine (anticholinergic)","Cyproheptadine (serotonin syndrome)","Gastric lavage","Intubation / airway management","Supportive care only"], group:"Plan", width:"full" },
      { id:"poison_control",label:"Poison Control Consulted?", type:"select",       required:true,  options:["Yes — 1-800-222-1222","No"], group:"Plan", width:"half" },
      { id:"psych_eval",  label:"Psychiatry Evaluation",        type:"select",       required:true,  options:["Ordered — pending","Completed — admit voluntarily","Completed — involuntary hold","Deferred — medical clearance first","Not indicated"], group:"Plan", width:"half" },
      { id:"disposition", label:"Disposition",                  type:"select",       required:true,  options:["ICU — unstable","Telemetry — QTc/arrhythmia concern","Medicine floor — NAC protocol","Inpatient Psychiatry — after medical clearance","Medical clearance complete — psych hold","Discharge — unintentional low-risk"], group:"Plan", width:"full" },
    ],
    ai_prompt_template: "Generate a professional ED Overdose/Toxicology evaluation note. CC={{cc}}, Intent={{intent}}, Substance={{substance}}, Time={{time_ingestion}}, PMH={{pmh}}, Vitals={{vitals}}, Toxidrome={{toxidrome}}, Exam={{exam}}, EtOH={{etoh}} mg/dL, APAP={{apap}} mcg/mL, ASA={{asa}}, ECG={{ekg}}, Treatment={{treatment}}, Poison Control={{poison_control}}, Psych={{psych_eval}}, Disposition={{disposition}}. Include Rumack-Matthew nomogram interpretation for acetaminophen if applicable. Clear documentation of suicide risk assessment if intentional."
  },

  {
    id: "tpl-006", template_key: "icu-daily-progress",
    name: "ICU — Daily Progress Note",
    description: "Systematic ICU daily note: organ system review, goals, plan",
    specialty: "Critical Care/ICU", setting: "ICU", note_type: "Progress Note", icon: "🏥",
    tags: ["ICU","critical care","daily note","organ systems","ventilator"],
    fields: [
      { id:"events_24h",   label:"Significant Events in Past 24h",   type:"textarea",  required:true,  placeholder:"Clinical events, procedures, changes…", group:"Overview",  width:"full" },
      { id:"vitals",       label:"Vitals (24h Range)",                type:"vitals_block",required:true,                                                    group:"Overview",  width:"full" },
      { id:"neuro",        label:"Neurological",                      type:"textarea",  required:true,  placeholder:"GCS, sedation (RASS), agitation (CAM-ICU), pain (CPOT)…", group:"Systems", width:"full" },
      { id:"resp_mode",    label:"Respiratory — Ventilator Mode",     type:"select",    required:false, options:["Spontaneous breathing","HFNC","BiPAP/NIV","AC/VC","AC/PC","PSV","CPAP","Extubated today","Not on vent"], group:"Systems", width:"half" },
      { id:"resp_settings",label:"Vent Settings (if intubated)",      type:"text",      required:false, placeholder:"FiO₂ 40%, PEEP 8, TV 450, RR 16", group:"Systems",    width:"half" },
      { id:"cardio",       label:"Cardiovascular",                    type:"textarea",  required:true,  placeholder:"HR, rhythm, BP, vasopressor requirements, MAP goal…", group:"Systems", width:"full" },
      { id:"renal",        label:"Renal / Fluids",                    type:"textarea",  required:true,  placeholder:"UO (mL/kg/hr), net I&O, creatinine trend, electrolytes…", group:"Systems", width:"full" },
      { id:"gi",           label:"GI / Nutrition",                    type:"textarea",  required:false, placeholder:"Bowel function, enteral/parenteral nutrition, HOB status…", group:"Systems", width:"full" },
      { id:"id",           label:"Infectious Disease / Antimicrobials",type:"textarea", required:false, placeholder:"Cultures pending/resulted, antibiotics (day X of Y), WBC…", group:"Systems", width:"full" },
      { id:"lines",        label:"Lines / Tubes / Drains",            type:"textarea",  required:true,  placeholder:"ETT (cm at lip), CVC (site, day X), foley, arterial line…", group:"Systems", width:"full" },
      { id:"assessment",   label:"Assessment",                        type:"textarea",  required:true,  placeholder:"Overall trajectory — improving / stable / worsening. Primary diagnosis.", group:"Plan", width:"full" },
      { id:"daily_goals",  label:"Daily Goals",                       type:"textarea",  required:true,  placeholder:"Wean FiO₂, target MAP > 65 off pressors, diurese 1L…", group:"Plan",    width:"full" },
      { id:"goc",          label:"Goals of Care",                     type:"select",    required:true,  options:["Full aggressive — resuscitate / intubate","Full code — no escalation","DNR only","DNR/DNI","Comfort measures only","Family meeting pending"], group:"Plan", width:"full" },
    ],
    ai_prompt_template: "Generate a comprehensive ICU daily progress note in organ-system format. 24h Events={{events_24h}}, Vitals={{vitals}}, Neuro={{neuro}}, Resp Mode={{resp_mode}} Settings={{resp_settings}}, Cardiovascular={{cardio}}, Renal/Fluids={{renal}}, GI={{gi}}, ID={{id}}, Lines/Tubes={{lines}}, Assessment={{assessment}}, Daily Goals={{daily_goals}}, Goals of Care={{goc}}. Professional, systematic ICU note organized by organ system with problem-numbered plan."
  },
];