// boardOrderCatalog.js — shared quick-pick order catalog for the in-board
// surfaces (CommandCenter OrdersTab + RapidOrderDrawer). Lightweight tap-to-
// queue lists with `common` flags and protocol sets. Intentionally SEPARATE
// from orderCatalog.js, which is the weight-based dosing / CPOE composer source.
export const BOARD_ORDERS = {
  labs:[
    { id:"bmp",      name:"BMP",                             common:true  },
    { id:"cbc",      name:"CBC w/ Differential",             common:true  },
    { id:"bmp-cbc",  name:"BMP + CBC",                       common:true  },
    { id:"trop",     name:"Troponin I (High-Sensitivity)",   common:true  },
    { id:"lactate",  name:"Lactate",                         common:true  },
    { id:"ua",       name:"Urinalysis w/ Reflex Culture",    common:true  },
    { id:"bc",       name:"Blood Cultures x2",               common:false },
    { id:"lfts",     name:"Hepatic Function Panel",          common:false },
    { id:"coags",    name:"PT / INR / PTT",                  common:false },
    { id:"ddimer",   name:"D-Dimer",                         common:false },
    { id:"tsh",      name:"TSH",                             common:false },
    { id:"lipase",   name:"Lipase",                          common:false },
    { id:"bhcg",     name:"β-hCG (Serum)",                   common:false },
    { id:"apap",     name:"Acetaminophen Level",             common:false },
    { id:"etoh",     name:"Ethanol Level",                   common:false },
    { id:"vbg",      name:"Venous Blood Gas",                common:false },
    { id:"abg",      name:"Arterial Blood Gas",              common:false },
  ],
  imaging:[
    { id:"cxr",      name:"CXR PA & Lateral",                common:true  },
    { id:"ct-head",  name:"CT Head w/o Contrast",            common:true  },
    { id:"ct-pe",    name:"CT Chest CTA (PE Protocol)",      common:true  },
    { id:"ct-ap",    name:"CT Abd/Pelvis w/ Contrast",       common:true  },
    { id:"us-ruq",   name:"US Abdomen RUQ",                  common:true  },
    { id:"cxr-p",    name:"CXR Portable AP",                 common:false },
    { id:"ct-headc", name:"CT Head w/ Contrast",             common:false },
    { id:"ct-csp",   name:"CT C-Spine w/o",                  common:false },
    { id:"ct-chest", name:"CT Chest w/o (Routine)",          common:false },
    { id:"ct-apo",   name:"CT Abd/Pelvis w/o",               common:false },
    { id:"us-pelv",  name:"US Pelvis (Transvaginal)",        common:false },
    { id:"us-dvt",   name:"US Lower Extremity DVT",          common:false },
    { id:"us-renal", name:"US Renal",                        common:false },
    { id:"xr-ankle", name:"XR Ankle",                        common:false },
    { id:"xr-wrist", name:"XR Wrist",                        common:false },
    { id:"xr-hand",  name:"XR Hand",                         common:false },
  ],
  meds:[
    { id:"keto",     name:"Ketorolac 30mg IV",               common:true  },
    { id:"zofran",   name:"Ondansetron 4mg IV",              common:true  },
    { id:"morph",    name:"Morphine 4mg IV",                 common:true  },
    { id:"dilaud",   name:"HYDROmorphone 0.5mg IV",          common:true  },
    { id:"ns1l",     name:"Normal Saline 1L IV Bolus",       common:true  },
    { id:"asa",      name:"Aspirin 324mg PO",                common:true  },
    { id:"alb",      name:"Albuterol 2.5mg Neb",             common:true  },
    { id:"ativan",   name:"LORazepam 2mg IV",                common:false },
    { id:"plavix",   name:"Clopidogrel 600mg PO",            common:false },
    { id:"hep",      name:"Heparin IV (ACS Weight-Based)",   common:false },
    { id:"solumed",  name:"Methylprednisolone 125mg IV",     common:false },
    { id:"benadryl", name:"DiphenhydrAMINE 50mg IV",         common:false },
    { id:"metro",    name:"Metoprolol 5mg IV",               common:false },
    { id:"adeno",    name:"Adenosine 6mg IV (Rapid Push)",   common:false },
    { id:"mag",      name:"Magnesium Sulfate 2g IV",         common:false },
    { id:"d5w",      name:"D5W 250mL IV",                    common:false },
  ],
  consults:[
    { id:"cards",    name:"Cardiology",                      common:true  },
    { id:"neuro",    name:"Neurology",                       common:true  },
    { id:"surg",     name:"General Surgery",                 common:true  },
    { id:"ortho",    name:"Orthopedics",                     common:false },
    { id:"psych",    name:"Psychiatry",                      common:false },
    { id:"obgyn",    name:"OB / GYN",                        common:false },
    { id:"uro",      name:"Urology",                         common:false },
    { id:"neph",     name:"Nephrology",                      common:false },
    { id:"gi",       name:"Gastroenterology",                common:false },
    { id:"pulm",     name:"Pulmonology",                     common:false },
    { id:"id-cons",  name:"Infectious Disease",              common:false },
    { id:"heme",     name:"Hematology / Oncology",           common:false },
  ],
  sets:[
    { id:"s-acs",    name:"ACS Protocol",       sub:"ASA · Troponin · CXR · Heparin",              items:["asa","trop","cxr","hep"]           },
    { id:"s-sepsis", name:"Sepsis Bundle",       sub:"Blood Cx x2 · Lactate · BMP · CBC · NS 1L",  items:["bc","lactate","bmp","cbc","ns1l"]  },
    { id:"s-stroke", name:"Stroke Protocol",     sub:"CT Head · BMP · CBC · Coags",                items:["ct-head","bmp","cbc","coags"]      },
    { id:"s-chest",  name:"Chest Pain W/U",      sub:"Troponin · CXR · BMP · Ketorolac",           items:["trop","cxr","bmp","keto"]          },
    { id:"s-pe",     name:"PE Protocol",         sub:"D-Dimer · CTA Chest · BMP",                  items:["ddimer","ct-pe","bmp"]             },
    { id:"s-sync",   name:"Syncope W/U",         sub:"BMP · CBC · Troponin · CXR",                 items:["bmp","cbc","trop","cxr"]           },
    { id:"s-abd",    name:"Abdominal Pain W/U",  sub:"BMP · CBC · Lipase · LFTs · CT Abd/Pelvis",  items:["bmp","cbc","lipase","lfts","ct-ap"]},
    { id:"s-uti",    name:"UTI / Urosepsis",     sub:"UA w/ Reflex · Blood Cx x2 · BMP · CBC",     items:["ua","bc","bmp","cbc"]              },
  ],
};
export const BOARD_ORDERS_FLAT = Object.entries(BOARD_ORDERS).reduce(
  (acc, [key, arr]) => { if (key !== "sets") arr.forEach(o => { acc[o.id] = o; }); return acc; },
  {}
);